services:
  postgresql:
    environment:
      # - POSTGRES_PASSWORD_FILE=/run/secrets/db_root_password
      - POSTGRES_PASSWORD=${LNMP_POSTGRES_PASSWORD:-mytest}
      - POSTGRES_DB=${LNMP_POSTGRES_DB:-postgres}
      - POSTGRES_USER=${LNMP_POSTGRES_USER:-postgres}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${LNMP_POSTGRES_DB:-postgres}", "-U", "${LNMP_POSTGRES_USER:-postgres}"]
      retries: 3
      timeout: 5s
