

x-common:
  &common
  restart: always
  env_file: ./scripts/cli/timezone.env
  networks:
    - backend
  # dns:
  #   - ${DNS:-114.114.114.114}

x-common-label:
  &common-label
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=${APP_ENV:-development}

services:
  postgresql:
    << :
      - *common
      - *common-label
    image: ${LNMP_LIBRARY_NS:-library}/postgres:${LNMP_POSTGRESQL_VERSION:-14.0}-alpine
    volumes:
      - type: volume
        source: postgresql-data
        target: /var/lib/postgresql/data
    ports:
      - "${LNMP_POSTGRESQL_PORT:-127.0.0.1:5432}:5432"

volumes:
  postgresql-data:
    << : *common-label
