#!/bin/bash

complete -W "backup \
        build \
        build-config \
        cleanup \
        composer \
        development \
        down \
        docs \
        help \
        laravel \
        laravel-artisan \
        php \
        production \
        production-config \
        push \
        restore \
        swarm-build \
        swarm-push \
        swarm-deploy \
        swarm-down \
        memcached-cli \
        mongo-cli \
        mysql-cli \
        nginx-cli \
        php-cli \
        phpmyadmin-cli \
        postgres-cli \
        rabbitmq-cli \
        redis-cli \
        update \
        upgrade \
        init \
        commit \
        test \
        dockerfile-update \
        debug \
        cn-mirror \
        compose" lnmp-docker.sh
