#!/bin/bash

complete -W "acme.sh \
        apache-config \
        backup \
        build \
        build-config \
        cleanup \
        config \
        daemon-socket \
        development \
        development-pull \
        down \
        docs \
        full-up \
        help \
        k8s \
        k8s-down \
        new \
        push \
        restore \
        restart \
        registry \
        registry-down \
        ssl \
        ssl-self \
        swarm-build \
        swarm-config \
        swarm-deploy \
        swarm-down \
        swarm-ps \
        swarm-pull \
        swarm-push \
        tp \
        apache-cli \
        mariadb-cli \
        memcached-cli \
        mongo-cli \
        mysql-cli \
        nginx-cli \
        nginx-config \
        php-cli \
        phpmyadmin-cli \
        postgres-cli \
        rabbitmq-cli \
        redis-cli \
        update \
        upgrade \
        init \
        commit \
        test \
        dockerfile-update \
        cn-mirror \
        compose" lnmp-docker.sh
