x-common:
  &common
  restart: always
  env_file: ./scripts/cli/timezone.env
  networks:
    - backend
  # dns:
  #   - ${DNS:-114.114.114.114}

x-common-label:
  &common-label
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=${APP_ENV:-development}

services:

  mariadb:
    << :
      - *common
      - *common-label
    image: "${LNMP_LIBRARY_NS:-library}/mariadb:${LNMP_MARIADB_VERSION:-10.11.5}"
    environment:
      MYSQL_DATABASE: ${LNMP_MYSQL_DATABASE:-test}
    ports:
      - "${LNMP_MYSQL_PORT:-127.0.0.1:3306}:3306"
    volumes:
      - type: volume
        source: mariadb-data
        target: ${LNMP_MARIADB_DATA:-/var/lib/mysql}
    command:
      - mysqld
      - --character-set-server=utf8mb4
    secrets:
      - mariadb_db_root_password

secrets:
  mariadb_db_root_password:
    << : *common-label
    file: ./secrets/${LNMP_DB_ROOT_PASSWORD_PATH:-db_root_password.txt}

volumes:
  mariadb-data:
    << : *common-label
