#
# khs1994.com Docker Swarm mode
# @link https://docs.docker.com/engine/swarm/
#
# $ ./lnmp-docker swarm-config
# $ docker compose -f docker-lnmp.swarm.deploy.yml build
# $ docker compose -f docker-lnmp.swarm.deploy.yml push
#
# $ docker stack deploy -c docker-lnmp.swarm.deploy.yml lnmp
# $ docker stack ps lnmp
#
# 1. less `volumes`
# 2. config put `configs`
# 3. secrets put `secrets`
# 4. use log driver journald
#
# tips:
# 1. `docker stack deploy` not support env
#
#
# Don't edit this file,please edit `docker-lnmp.swarm.yml`
#

x-logging:
  &default-logging
  driver: journald

x-labels:
  &default-labels
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=${APP_ENV:-swarm}

x-deploy:
  &default-deploy
  restart_policy:
    condition: any
    delay: 25s
    max_attempts: 5
    window: 123s
  update_config:
    parallelism: 2
    delay: 10s
    order: stop-first

x-build:
  &default-build
  # Dockerfile: my.Dockerfile
  args:
    ALPINE_URL: mirrors.aliyun.com # dl-cdn.alpinelinux.org

x-build-debian:
  &default-build-debian
  # Dockerfile: my.Dockerfile
  args:
    DEB_URL: mirrors.ustc.edu.cn # deb.debian.org
    DEB_SECURITY_URL: mirrors.ustc.edu.cn/debian-security/ # security.debian.org

services:

  mysql:
    build:
      << : *default-build-debian
      context: ./dockerfile/mysql/
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /etc/db_root_password
      MYSQL_DATABASE: test
    # ports:
    #   - "127.0.0.1:3306:3306"
    volumes:
      - ./scripts/backup/init.production:/docker-entrypoint-initdb.d:ro
      - ./scripts/backup/mysql:/backup
      - var-log-mysql:/var/log/mysql
    command: ["mysqld","--character-set-server=utf8mb4","--default-authentication-plugin=mysql_native_password"]
    # logging: *default-logging
    deploy:
      << : [*default-deploy,*default-labels]
      placement:
        constraints: [node.role == manager]
      # resources:
      #   limits:
      #     cpus: '0.50'
      #     memory: 50M
      #   reservations:
      #     cpus: '0.25'
      #     memory: 20M
    secrets:
      - source: db_root_password
        target: /etc/db_root_password
    configs:
      - source: mysql_conf_d_docker_cnf
        target: /etc/mysql/conf.d/docker.cnf
        mode: 0644
        uid: "0"
        gid: "0"

  redis:
    build:
      << : *default-build
      # << : *default-build-debian
      context: ./dockerfile/redis/
      dockerfile: Dockerfile
    # ports:
    #   - "127.0.0.1:6379:6379"
    volumes:
      - var-log-redis:/var/log/redis
    command: [
      "redis-server",
      "/redis.conf",
      "--daemonize no",
      "--bind 0.0.0.0",
      "--appendonly yes",
      # "--save \"\"",
      "--aof-use-rdb-preamble yes"
      ]
    # logging: *default-logging
    deploy:
      << :
        - *default-deploy
        - *default-labels
      # replicas: 2
      placement:
        constraints: [node.role == manager]
    configs:
      - source: redis_conf
        target: /redis.conf

  php8:
    volumes:
    # s6
    # - ./config/s6/s6-overlay/s6-rc.d:/etc/s6-overlay/s6-rc.d
    # - ./config/s6/s6-overlay/scripts:/etc/s6-overlay/scripts
    # - ./config/crontabs/root:/etc/crontabs/root.s6
    - var-log-php:/var/log
    configs:
    - source: php_ini
      target: /usr/local/etc/php/php.ini
    - source: php_ini_include
      target: /usr/local/etc/php/conf.d/zz-docker-php.ini
    - source: php_fpm_conf_d_zz_docker_conf
      target: /usr/local/etc/php-fpm.d/zz-docker.conf
    secrets:
    - source: ssh_id_rsa
      target: /root/.ssh/id_rsa
      mode: 0600
    - source: ssh_config
      target: /root/.ssh/config
    depends_on:
    - mysql
    - redis
    # networks:
    # - backend
    deploy:
      << :
        - *default-deploy
        - *default-labels
      # replicas: 2
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  nginx:
    build:
      << : *default-build
      # << : *default-build-debian
      # context: ./dockerfile/nginx/
      context: ./config/nginx
      dockerfile: Dockerfile
    # ports:
    #   - "443:443/tcp"
    #   - "443:443/udp"
    #   - "80:80"
    volumes:
      # - ./app:/app
      # - ./config/nginx:/etc/nginx/conf.d:ro
      - var-log-nginx:/var/log/nginx
    # networks:
    #   - frontend
    # depends_on:
    #   - php7
    #     # condition: service_completed_successfully
    #       # service_started service_healthy service_completed_successfully
    #   - minio
    # logging: *default-logging
    deploy:
      << :
        - *default-deploy
        - *default-labels
      # replicas: 2
      placement:
        constraints: [node.role == manager]
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
        # uid: '103'
        # gid: '103'
        # mode: 0440
      # one domain one conf file
      - source: nginx_80_conf
        target: /etc/nginx/conf.d/80.conf
      - source: nginx_301_conf
        target: /etc/nginx/conf.d/301.conf
      - source: nginx_ssl_conf
        target: /etc/nginx/conf.d/ssl.config
      - source: nginx_khs1994_com_conf
        target: /etc/nginx/conf.d/khs1994.com.conf
    secrets:
      #
      # ECC + RSA
      #
      # @link https://github.com/khs1994-docker/lnmp/issues/239
      #
      - source: khs1994_com_ssl_crt
        target: /etc/nginx/conf.d/ssl/khs1994.com.crt
      - source: khs1994_com_ssl_key
        target: /etc/nginx/conf.d/ssl/khs1994.com.key
      - source: khs1994_com_ssl_rsa_crt
        target: /etc/nginx/conf.d/ssl/khs1994.com.rsa.crt
      - source: khs1994_com_ssl_rsa_key
        target: /etc/nginx/conf.d/ssl/khs1994.com.rsa.key
      # - source: developer_khs1994_com_ssl_crt
      #   target: /etc/nginx/conf.d/ssl/developer.khs1994.com.crt
      # - source: developer_khs1994_com_ssl_key
      #   target: /etc/nginx/conf.d/ssl/developer.khs1994.com.key
      # - source: developer_khs1994_com_ssl_rsa_crt
      #   target: /etc/nginx/conf.d/ssl/developer.khs1994.com.rsa.crt
      # - source: developer_khs1994_com_ssl_rsa_key
      #   target: /etc/nginx/conf.d/ssl/developer.khs1994.com.rsa.key
      # - source: auth_htpasswd
      #   target: /etc/nginx/conf.d/auth/nginx.htpasswd
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

networks:
  frontend:
    << : *default-labels
    attachable: true
  backend:
    << : *default-labels
    attachable: true

volumes:
  mysql-data:
    << : *default-labels
  redis-data:
    << : *default-labels
  zoneinfo-data:
    << : *default-labels
  minio-data:
    << : *default-labels
  var-log-php:
    << : *default-labels
  var-log-nginx:
    << : *default-labels
  var-log-redis:
    << : *default-labels
  var-log-mysql:
    << : *default-labels

secrets:
  db_root_password:
    << : *default-labels
    file: secrets/db_root_password.txt
  # ECC + RSA
  khs1994_com_ssl_key:
    << : *default-labels
    file: ./config/nginx/ssl/khs1994.com.key
  khs1994_com_ssl_crt:
    << : *default-labels
    file: ./config/nginx/ssl/khs1994.com.crt
  khs1994_com_ssl_rsa_key:
    << : *default-labels
    file: ./config/nginx/ssl/khs1994.com.rsa.key
  khs1994_com_ssl_rsa_crt:
    << : *default-labels
    file: ./config/nginx/ssl/khs1994.com.rsa.crt
  #
  # developer_khs1994_com_ssl_crt:
  #   file: ./config/nginx/ssl/developer.khs1994.com.crt
  #   << : *default-labels
  #
  # developer_khs1994_com_ssl_key:
  #   file: ./config/nginx/ssl/developer.khs1994.com.key
  #   << : *default-labels
  #
  # developer_khs1994_com_ssl_rsa_crt:
  #   file: ./config/nginx/ssl/developer.khs1994.com.rsa.crt
  #   << : *default-labels
  #
  # developer_khs1994_com_ssl_rsa_key:
  #   file: ./config/nginx/ssl/developer.khs1994.com.rsa.key
  #   << : *default-labels
  #
  # auth_htpasswd:
  #   file: ./config/nginx/auth/nginx.htpasswd
  #   << : *default-labels
  # SSH use in  CI/CD
  ssh_id_rsa:
    file: /root/.ssh/id_rsa
    << : *default-labels
  # SSH config
  ssh_config:
    file: ./secrets/ssh_config
    << : *default-labels

configs:
  mysql_conf_d_docker_cnf:
    file: ./config/mysql/docker.production.cnf
    << : *default-labels
  nginx_conf:
    file: ./config/etc/nginx/nginx.production.conf
    << : *default-labels
  nginx_80_conf:
    file: ./config/nginx/80.conf
    << : *default-labels
  nginx_301_conf:
    file: ./config/nginx/301.conf
    << : *default-labels
  nginx_ssl_conf:
    file: ./config/nginx/ssl.config
    << : *default-labels
  nginx_khs1994_com_conf:
    file: ./config/nginx/khs1994.com.conf
    << : *default-labels
  php_ini:
    file: ./config/php8/php.production.ini
    << : *default-labels
  php_development_ini:
    file: ./config/php8/php.development.ini
    << : *default-labels
  php_ini_include:
    file: ./config/php8/docker-php.ini
    << : *default-labels
  php_fpm_conf_d_zz_docker_conf:
    file: ./config/php8/zz-docker.production.conf
    << : *default-labels
  redis_conf:
    file: ./config/redis/redis.production.conf
    << : *default-labels
