x-common-labels:
  &common-labels
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=${APP_ENV:-development}

x-common:
  &common
  restart: ${LNMP_RESTART:-always}
  env_file: ./scripts/cli/timezone.env
  networks:
    - backend
  read_only: ${LNMP_ROOT_FILESYSTEM_READ_ONLY:-false}
  # dns:
  #   - ${DNS:-114.114.114.114}

x-tmpfs:
  &tmpfs
  type: tmpfs
  target: /run
  # tmpfs:
  #   size: 1000

services:
  mysql:
    << : [*common,*common-labels]
    image: "${LNMP_LIBRARY_NS:-library}/mysql:${LNMP_MYSQL_VERSION:-8.0.33}"
    environment:
      MYSQL_DATABASE: ${LNMP_MYSQL_DATABASE:-test}
    ports:
      - "${LNMP_MYSQL_PORT:-127.0.0.1:3306}:3306"
      - "${LNMP_MYSQL_PORT_X:-127.0.0.1:33060}:33060"
    volumes:
      - type: volume
        source: mysql-data
        target: ${LNMP_MYSQL_DATA:-/var/lib/mysql}
      - type: tmpfs
        target: /var/run/mysqld
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${LNMP_MYSQL_ROOT_PASSWORD:-mytest}"]
      retries: 3
      timeout: 5s

  redis:
    << : [*common,*common-labels]
    image: "${LNMP_LIBRARY_NS:-library}/redis:${LNMP_REDIS_VERSION:-7.0.0}-alpine"
    ports:
      - "${LNMP_REDIS_PORT:-127.0.0.1:6379}:6379"
    volumes:
      # - redis-data:/data
      - type: volume
        source: redis-data
        target: /data
        volume:
          nocopy: true
      - << : *tmpfs
    command: [
      "redis-server",
      "/redis.conf",
      "--daemonize no",
      "--logfile /var/log/redis/redis.log",
      "--bind 0.0.0.0",
      "--appendonly yes",
      # "--save \"\"",
      "--aof-use-rdb-preamble yes"
      ]
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      retries: 3
      timeout: 5s

  php8:
    &php8
    << : [*common,*common-labels]
    image: "${LNMP_DOCKER_IMAGE_PREFIX:-khs1994}/php:${LNMP_PHP8_VERSION:-8.4.11}-fpm-alpine"
    volumes:
      - type: volume
        source: zoneinfo-data
        target: /usr/share/zoneinfo
        volume:
          nocopy: false
    networks:
      # - frontend
      # - backend
      frontend:
        aliases:
        - php
      backend:
        aliases:
        - php
    tmpfs: /run:exec
    expose:
      - "9000"
    environment:
      - &lnmp_version LNMP_VERSION=${LNMP_VERSION:-v24.11} x86_64 With Pull Docker Image
      - APP_ENV=${APP_ENV:-development}
      - LNMP_OPCACHE_ENABLE=${LNMP_OPCACHE_ENABLE:-1}
      - PATH=/command:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      # - XDEBUG_MODE

  nginx:
    << : [*common,*common-labels]
    image: "${LNMP_LIBRARY_NS:-library}/nginx:${LNMP_NGINX_VERSION:-1.29.1}-alpine"
    ports:
      - "${LNMP_NGINX_HTTPS_PORT:-0.0.0.0:443}:443/udp"
      - "${LNMP_NGINX_HTTPS_PORT:-0.0.0.0:443}:443/tcp"
      - "${LNMP_NGINX_HTTP_PORT:-0.0.0.0:80}:80"
    volumes:
      - << : *tmpfs
    working_dir: /app
    networks:
      - frontend
    healthcheck:
      test: ["CMD","nginx","-t"]

networks:
  frontend:
    << : *common-labels
  backend:
    << : *common-labels

volumes:
  mysql-data:
    << : *common-labels
  redis-data:
    << : *common-labels
  zoneinfo-data:
    << : *common-labels
