#!/usr/bin/env bash

# git remote add origin git@github.com:khs1994-docker/lnmp.git
# git remote add aliyun git@code.aliyun.com:khs1994-docker/lnmp.git
# git remote add tgit git@git.qcloud.com:khs1994-docker/lnmp.git
# git remote add coding git@git.coding.net:khs1994/lnmp.git

# Don't Run this shell script on git bash Windows, please use ./lnmp-docker.ps1

#
# sudo ? only need by install docker-compose
#

set -e

if [ `uname -s` != 'Darwin' ] && [ `uname -s` != 'Linux' ];then \
    echo -e "\n\033[31mError \033[0m  Please use ./lnmp-docker.ps1 on PowerShell in Windows"; exit 1; fi

print_info(){
  echo -e "\033[32mINFO \033[0m  $@"
}

print_error(){
  echo -e "\033[31mERROR\033[0m  $@"
  export exit_by_error=1
}

print_warning(){
  echo -e "\033[33mWARNING\033[0m  $@"
}

NOTSUPPORT(){
  print_error "Not Support ${OS} ${ARCH}\n"
  exit 1
}

check_nginx_conf(){
  set +e
  echo "$LNMP_INCLUDE" | grep 'minio' > /dev/null 2>&1 || ( ls config/${LNMP_NGINX_CONF_D:-nginx}/minio.conf > /dev/null 2>&1 \
    && ( print_error "your .env file not include minio, but nginx conf.d folder include minio.conf" ; echo))
  set -e
}

_check_and_copy_file(){
  if ! [ -f $2 ];then cp $1 $2 ; fi
}

if [ -f cli/khs1994-robot.enc ];then
    print_info "Use LNMP CLI in LNMP Root $PWD\n"
else
    if ! [ -z "${LNMP_PATH}" ];then
      # 存在环境变量，进入
      print_info "Use LNMP CLI in $PWD\n"
      cd ${LNMP_PATH}
    else
      print_error  "You must set system env LNMP_PATH, please see cli/README.md"
      exit 1
    fi
fi

if ! [ -f docker-compose.include.yml ];then
  cp docker-compose.include.example.yml docker-compose.include.yml
fi

if [ -f lnmp-custom-script ];then
  . ./lnmp-custom-script
fi

if ! [ -f config/php/docker-php.ini ];then
  cp config/php/docker-php.ini.example config/php/docker-php.ini
fi

_check_and_copy_file config/composer/config.example.json config/composer/config.json

# PHPer command

if [ -z "$LNMP_PATH" ];then print_warning "Try lnmp-* commands? Please see cli/README.md\n"; fi

help(){
  echo  -e "
Docker-LNMP CLI ${LNMP_DOCKER_VERSION}

Official WebSite https://lnmp.khs1994.com

Usage: ./docker-lnmp COMMAND

PCIT EE:
  pcit-up              Up(Run) PCIT EE https://github.com/pcit-ce/pcit
  pcit-cp              Copy PCIT files to app/.pcit

Commands:
  acme.sh              Run original acme.sh command to issue SSL certificate
  backup               Backup MySQL databases
  build                Build or rebuild LNMP Self Build images (Only Support x86_64)
  build-config         Validate and view the LNMP Self Build images Compose file
  build-push           Build and Pushes images to Docker Registory (Only Support x86_64)
  build-up             Create and start LNMP containers With Self Build images (Only Support x86_64)
  cleanup              Cleanup log files
  compose              Install docker-compose [ --official | -f ]
  completion           Move fish shell completion code (Only Support fish)
  up                   Up LNMP
  config               Validate and view the LNMP Compose file
  pull                 Pull LNMP Docker Images
  debug                Generate Debug information, then copy it to GitHub Issues
  daemon-socket        Expose Docker daemon on tcp://0.0.0.0:2375 without TLS on macOS
  daemon-tls           Display how to enable Docker TLS Daemon
  daemon-tls-cert      Generate Docker Daemon TLS cert
  down                 Stop and remove LNMP Docker containers, networks
  docs                 Read support documents
  help                 Display this help message
  nfs                  Up NFS server [ down | ]
  init                 Init LNMP environment
  restore              Restore MySQL databases
  restart              Restart LNMP services
  registry-up          Up Docker Registry
  registry-down        Stop Docker Registry
  update               Upgrades LNMP [ -f | ]
  upgrade              Upgrades LNMP [ -f | ]
  update-version       Update LNMP soft to latest vesion

PHP Tools:
  httpd-config         Generate Apache2 vhost conf
  new                  New PHP Project and generate nginx conf and issue SSL certificate
  nginx-config         Generate nginx vhost conf
  ssl                  Issue SSL certificate powered by acme.sh, Thanks Let's Encrypt
  ssl-self             Issue Self-signed SSL certificate

Composer:
 satis                 Build Satis

Kubernets:
  dashboard            Print how run kubernetes dashboard in Docker for Desktop
  gcr.io               Up local gcr.io(k8s.gcr.io) registry server to start Docker for Desktop Kubernetes [ --no-pull | ]

Swarm mode:
  swarm-build          Build Swarm mode LNMP images (nginx php7)
  swarm-config         Validate and view the Swarm mode Compose file
  swarm-deploy         Deploy LNMP stack IN Swarm mode
  swarm-down           Remove LNMP stack IN Swarm mode
  swarm-ps             List the LNMP tasks
  swarm-pull           Pull LNMP Docker Images IN Swarm mode
  swarm-push           Push Swarm mode LNMP images (nginx php7)
  swarm-update         Print update LNMP service example

Container Tools:
  SERVICE-cli          Execute a command in a running LNMP container
  SERVICE-container-id Display SERVICE container id
  SERVICE-logs         Print LNMP containers logs (journald) [-f | ]

ClusterKit:
  clusterkit-help      Print ClusterKit help info

Developer Tools:
  cn-mirror            Push master branch to CN mirror
  test                 Test LNMP
  cookbooks            Up local cookbooks server

AD:
  haokan               Baidu haokan
  alipay               Alipay

Read './docs/*.md' for more information about CLI commands.

You can open issue in [ https://github.com/khs1994-docker/lnmp/issues ] when you meet problems.

You must Update .env file when update this project.

Donate https://zan.khs1994.com

AD Tencent Kubernetes Engine http://dwz.cn/I2vYahwq
"
}

_tongji(){
  if ! [ -f log/tongji.txt ];then
    print_info "Send OS type and IP data to khs1994-docker/lnmp, Thanks you help us improve\n"
    if [ -f /etc/os-release ];then . /etc/os-release ; fi
    curl -s -X GET --user-agent "${OS:-unkown os}-${ID:-unknow id}-${VERSION:-unkown version}" https://developer.khs1994.com/tongji/lnmp --connect-timeout 5 > /dev/null || echo 'ERROR=true' > log/tongji.txt
    TIMESTAMP=`date +%s`
    echo "TIMESTAMP=${TIMESTAMP}" > log/tongji.txt
  else
    . ./log/tongji.txt

    if [ `date +%s` -gt $((TIMESTAMP + 86400)) ];then
      rm -rf log/tongji.txt
      _tongji
    fi
  fi
}

clusterkit_help(){
exec echo "
ClusterKit:
  clusterkit [-d]              UP LNMP With Mysql Redis Memcached Cluster [Background]
  clusterkit-COMMAND           Run docker-compsoe commands(config, pull, etc)

  swarm-clusterkit             UP LNMP With Mysql Redis Memcached Cluster IN Swarm mode

  clusterkit-mysql-up          Up MySQL Cluster
  clusterkit-mysql-down        Stop MySQL Cluster
  clusterkit-mysql-exec        Execute a command in a running MySQL Cluster node

  clusterkit-mysql-deploy      Deploy MySQL Cluster in Swarm mode
  clusterkit-mysql-remove      Remove MySQL Cluster in Swarm mode

  clusterkit-memcached-up      Up memcached Cluster
  clusterkit-memcached-down    Stop memcached Cluster
  clusterkit-memcached-exec    Execute a command in a running memcached Cluster node

  clusterkit-memcached-deploy  Deploy memcached Cluster in Swarm mode
  clusterkit-memcached-remove  Remove memcached Cluster in Swarm mode

  clusterkit-redis-up          Up Redis Cluster(By Ruby)
  clusterkit-redis-down        Stop Redis Cluster(by Ruby)
  clusterkit-redis-exec        Execute a command in a running Redis Cluster node(By Ruby)

  clusterkit-redis-deploy      Deploy Redis Cluster in Swarm mode(By Ruby)
  clusterkit-redis-remove      Remove Redis Cluster in Swarm mode(By Ruby)

  clusterkit-redis-replication-up       Up Redis M-S (replication)
  clusterkit-redis-replication-down     Stop Redis M-S (replication)
  clusterkit-redis-replication-exec     Execute a command in a running Redis M-S (replication) node

  clusterkit-redis-replication-deploy   Deploy Redis M-S (replication) in Swarm mode
  clusterkit-redis-replication-remove   Remove Redis M-S (replication) in Swarm mode

  clusterkit-redis-sentinel-up           Up Redis S
  clusterkit-redis-sentinel-down         Stop Redis S
  clusterkit-redis-sentinel-exec         Execute a command in a running Redis S node

  clusterkit-redis-sentinel-deploy       Deploy Redis S in Swarm mode
  clusterkit-redis-sentinel-remove       Remove Redis S in Swarm mode

"
}

_gcr_io_down(){
  docker container rm -f $(docker container ls -a -f label=com.khs1994.lnmp.gcr.io -q) > /dev/null 2>&1 || echo > /dev/null
}

_gcr_io(){
  if [ "$1" = down ];then
    _gcr_io_down
    print_info "Stop k8s.gcr.io local server success"
    echo
    exit
  fi

  if [ "$1" = logs ];then
    exec docker container logs $(docker container ls -f label=com.khs1994.lnmp.gcr.io -q) -f
  fi

  _gcr_io_down
  echo ""
  echo "This local server support Docker Desktop v18.05-EDGE-67"
  echo ""

  mkdir -p data/registry

  docker run -it -d \
      -p 443:443 \
      -v $PWD/config/registry/config.gcr.io.yml:/etc/docker/registry/config.yml \
      -v $PWD/config/registry:/etc/docker/registry/ssl \
      -v $PWD/data/registry:/var/lib/registry:delegated \
      --label com.khs1994.lnmp.gcr.io \
      registry || quit=1

      if [ "$quit" = 1 ];then
        echo
        print_error "Please stop soft who bind 443 port first"
        echo
        exit 1
      fi

    if [ "$1" = '--no-pull' ];then
      return
    fi

    if [ "$OS" = 'Darwin' ];then
      cat ~/.docker/daemon.json | grep gcr.io > /dev/null || please_set=1

      if [ "$please_set" = 1 ];then echo; \
          print_error \
          "Please add gcr.io k8s.gcr.io as Insecure registries In [ Docker Menu -> preferences -> Daemon -> Basic -> Insecure registries ]"; \
          echo; exit; fi
    fi

    images="kube-controller-manager-amd64:v1.10.3 \
    kube-apiserver-amd64:v1.10.3 \
    kube-scheduler-amd64:v1.10.3 \
    kube-proxy-amd64:v1.10.3 \
    etcd-amd64:3.1.12 \
    k8s-dns-sidecar-amd64:1.14.8 \
    k8s-dns-kube-dns-amd64:1.14.8 \
    k8s-dns-dnsmasq-nanny-amd64:1.14.8 \
    pause-amd64:3.1"

    for image in $images
    do
       docker pull gcr.mirrors.ustc.edu.cn/$image
       docker tag gcr.mirrors.ustc.edu.cn/$image k8s.gcr.io/$image
       docker push k8s.gcr.io/$image
       docker rmi gcr.mirrors.ustc.edu.cn/$image
    done

    echo "
Warning

this command up a local server on port 443.

When Docker for Desktop Start Kubernetes Success, you must remove this local server.

\$ lnmp-docker gcr.io down

More information please see docs/kubernetes/docker-desktop.md

    "
}

_satis(){
  if ! [ -d ${APP_ROOT}/satis ];then
    cp -r app/satis-demo ${APP_ROOT}/satis
    print_warning "Please modify app/satis/satis.json\n"
  fi

  docker run --rm -it -v ${APP_ROOT}/satis:/build \
      -v lnmp_composer_cache-data:/composer composer/satis
}

_local_docs_server(){
  if ! [ -d ${APP_ROOT}/lnmp-docs/k8s ];then
    git clone --depth=1 -b gh-pages git@gitee.com:khs1994-website/kubernetes-handbook.git ${APP_ROOT}/lnmp-docs/k8s
  else
    git -C ${APP_ROOT}/lnmp-docs/k8s fetch --depth=1 origin gh-pages
    git -C ${APP_ROOT}/lnmp-docs/k8s reset --hard origin/gh-pages
  fi

  if ! [ -d ${APP_ROOT}/lnmp-docs/docker ];then
    git clone --depth=1 -b pages git@gitee.com:docker_practice/docker_practice.git ${APP_ROOT}/lnmp-docs/docker
  else
    git -C ${APP_ROOT}/lnmp-docs/docker fetch --depth=1 origin pages
    git -C ${APP_ROOT}/lnmp-docs/docker reset --hard origin/pages
  fi

  if ! [ -d ${APP_ROOT}/lnmp-docs/laravel ];then
    git clone --depth=1 -b gh-pages git@gitee.com:khs1994-website/laravel5.5-docs.zh-cn.git ${APP_ROOT}/lnmp-docs/laravel
  else
    git -C ${APP_ROOT}/lnmp-docs/laravel fetch --depth=1 origin gh-pages
    git -C ${APP_ROOT}/lnmp-docs/laravel reset --hard origin/gh-pages
  fi

  if ! [ -d ${APP_ROOT}/lnmp-docs/laravel-en ];then
    git clone --depth=1 -b gh-pages git@gitee.com:khs1994-website/laravel-docs.git ${APP_ROOT}/lnmp-docs/laravel-en
  else
    git -C ${APP_ROOT}/lnmp-docs/laravel-en fetch --depth=1 origin gh-pages
    git -C ${APP_ROOT}/lnmp-docs/laravel-en reset --hard origin/gh-pages
  fi

  if ! [ -d ${APP_ROOT}/lnmp-docs/nginx ];then
    git clone --depth=1 -b gh-pages git@gitee.com:khs1994-website/nginx-docs.zh-cn.git ${APP_ROOT}/lnmp-docs/nginx
  else
    git -C ${APP_ROOT}/lnmp-docs/nginx fetch --depth=1 origin gh-pages
    git -C ${APP_ROOT}/lnmp-docs/nginx reset --hard origin/gh-pages
  fi
}

_registry(){
  # SSL 相关
  if [ ! -f config/${LNMP_NGINX_CONF_D:-nginx}/ssl/${LNMP_REGISTRY_HOST}.crt ] \
      || [ ! -f config/${LNMP_NGINX_CONF_D:-nginx}/ssl/${LNMP_REGISTRY_HOST}.key ];then
    print_warning "Docker Registry SSL not found, generating ...."
    ssl_self $LNMP_REGISTRY_HOST
  fi

  if [ ! -f config/${LNMP_NGINX_CONF_D:-nginx}/ssl/${LNMP_REGISTRY_HOST}.crt ] \
      || [ ! -f config/${LNMP_NGINX_CONF_D:-nginx}/ssl/${LNMP_REGISTRY_HOST}.key ];then
    print_error "Docker Registry SSL error" ; exit 1
  else
    print_info "Docker Registry SSL Correct"
  fi

  # 生成 密码 验证文件
  if ! [ -f config/${LNMP_NGINX_CONF_D:-nginx}/auth/docker_registry.htpasswd ];then
    echo; print_info "First start, Please set username and password"
    read -p "username: " username
    if [ -z $username ];then echo; print_error "Please input username"; exit 1; fi
    read -s -p "password: " password; echo
    if [ -z $password ];then echo; print_error "Please input password"; exit 1; fi
    read -s -p "Please reinput password: " password_verify; echo; echo

    if ! [ "$password" = "$password_verify" ];then
      print_error "两次输入的密码不同，请再次执行 ./lnmp-docker registry 完成操作"; exit 1
    fi

    docker run --init --rm \
      --entrypoint htpasswd \
      registry \
      -Bbn $username $password > config/${LNMP_NGINX_CONF_D:-nginx}/auth/docker_registry.htpasswd
      # 部分 nginx 可能不能解密，你可以替换为下面的命令
      # -mbn username password > auth/nginx.htpasswd \
  fi

  # NGINX 配置文件
  if ! [ -f config/${LNMP_NGINX_CONF_D:-nginx}/${REGISTRY_CONF:-registry.conf} ];then
    if [ -f config/${LNMP_NGINX_CONF_D:-nginx}/registry.conf.backup ];then
      cp config/${LNMP_NGINX_CONF_D:-nginx}/registry.conf.backup config/${LNMP_NGINX_CONF_D:-nginx}/registry.conf
    else
      cp config/nginx/demo-registry.config config/${LNMP_NGINX_CONF_D:-nginx}/registry.conf
    fi
  fi

  sed -i '' "s#DOMAIN#${LNMP_REGISTRY_HOST}#g" config/${LNMP_NGINX_CONF_D:-nginx}/registry.conf

  exec docker-compose up -d registry nginx
}

_registry_down(){
  docker-compose stop registry
  docker-compose rm -f registry
  mv config/${LNMP_NGINX_CONF_D:-nginx}/registry.conf config/${LNMP_NGINX_CONF_D:-nginx}/registry.conf.backup
}

env_status(){
  # cp .env.example to .env
  if [ -f .env ];then \
      print_info ".env file existing\n"; \
  else print_warning ".env file NOT existing (Maybe First Run)\n"; cp .env.example .env ; fi

  _check_and_copy_file volumes/.env.example volumes/.env

  if ! [ -f secrets/minio/key.txt ];then
    cp secrets/minio/key.example.txt secrets/minio/key.txt
    cp secrets/minio/secret.example.txt secrets/minio/secret.txt
  fi

  if ! [ -f config/supervisord/supervisord.ini ];then
    cp config/supervisord/supervisord.ini.example config/supervisord/supervisord.ini
  fi
}

# 自动升级软件版本

update_version(){
  . ./.env.example

  local softs='PHP \
              NGINX \
              HTTPD \
              MYSQL \
              MARIADB \
              REDIS \
              MEMCACHED \
              RABBITMQ \
              POSTGRESQL \
              MONGODB \
              '
  for soft in $softs; do
    version="LNMP_${soft}_VERSION"
    eval version=$(echo \$$version)
    if [ $OS = "Darwin" ];then
      sed -i '' 's/^LNMP_'"${soft}"'_VERSION.*/LNMP_'"${soft}"'_VERSION='"${version}"'/g' .env
    else
      sed -i 's/^LNMP_'"${soft}"'_VERSION.*/LNMP_'"${soft}"'_VERSION='"${version}"'/g' .env
    fi
  done
}

# Docker 是否运行

run_docker(){
  docker info > /dev/null 2>&1 || (clear ; \
    echo "==========================" ;\
    echo "=== Please Run Docker ====" ;\
    echo "==========================" ;\
    exit 1)
}

# 创建日志文件

logs(){
  if ! [ -f log/supervisord.log ];then touch log/supervisord.log; fi
  if ! [ -d log/supervisord ];then mkdir -p log/supervisord; fi
  if ! [ -d log/httpd ];then mkdir -p log/httpd; fi
  if ! [ -d log/mongodb ];then mkdir -p log/mongodb && echo > log/mongodb/mongo.log; fi
  if ! [ -d log/mysql ];then mkdir -p log/mysql && echo > log/mysql/error.log; fi
  if ! [ -d log/mariadb ];then mkdir -p log/mariadb && echo > log/mariadb/error.log; fi
  if ! [ -d log/nginx ];then mkdir -p log/nginx && echo > log/nginx/error.log && echo > log/nginx/access.log; fi
  if ! [ -d log/nginx-unit ];then mkdir -p log/nginx-unit; fi
  if ! [ -d log/php ];then
    mkdir -p log/php \
      && echo > log/php/error.log \
      && echo > log/php/slow.log \
      && echo > log/php/php-fpm-access.log \
      && echo > log/php/php-fpm-error.log \
      && echo > log/php/xdebug-remote.log
  fi
  if ! [ -d log/redis ];then mkdir -p log/redis && echo > log/redis/redis.log ; fi
  chmod -R 777 log/mongodb \
               log/mysql \
               log/nginx \
               log/php \
               log/redis || sudo chmod -R 777 log/mongodb \
                                          log/mysql \
                                          log/nginx \
                                          log/php \
                                          log/redis
}

# 清理日志文件
cleanup(){
      logs \
      && echo > log/mongodb/mongo.log \
      && echo > log/mysql/error.log \
      && echo > log/mariadb/error.log \
      && echo > log/nginx/error.log \
      && echo > log/nginx/access.log \
      && echo > log/nginx-unit/nginx-unit.log \
      && echo > log/nginx-unit/access.log \
      && echo > log/php/php-fpm-access.log \
      && echo > log/php/php-fpm-error.log \
      && echo > log/php/error.log \
      && echo > log/php/slow.log \
      && echo > log/php/xdebug-remote.log \
      && echo > log/redis/redis.log \
      && rm -rf log/httpd/* \
      && rm -rf log/supervisord/* \
      && rm -rf log/supervisord.log \
      print_info "Clean log files SUCCESS\n"
}

gitbook(){
  docker rm -f lnmp-docs > /dev/null 2>&1 || echo
  exec docker run --init -it --rm -p 4000:4000 \
    --name lnmp-docs -v $PWD/docs:/srv/gitbook-src \
    khs1994/gitbook \
    server
}

# 将 compose 移入 PATH
install_docker_compose_move(){
  if [ -f /etc/os-release ];then
    . /etc/os-release
    case "$ID" in
      coreos )
        if ! [ -d /opt/bin ];then sudo mkdir -p /opt/bin; fi
        sudo install -m755 /tmp/docker-compose /opt/bin/docker-compose
        ;;
      * )
        sudo install -m755 /tmp/docker-compose /usr/local/bin/docker-compose > /dev/null 2>&1 \
            || install -m755 /tmp/docker-compose /usr/local/bin/docker-compose
        ;;
    esac
  else
    NOTSUPPORT
  fi
}

# 从 GitHub 安装 compose
install_docker_compose_official(){
  if [ "$OS" != 'Linux' ];then exit 1;fi
  curl -sL ${COMPOSE_LINK_OFFICIAL}/$LNMP_DOCKER_COMPOSE_VERSION/docker-compose-`uname -s`-`uname -m` \
      > /tmp/docker-compose || print_error "Download docker-compose error, code is $?\n"
  install_docker_compose_move
}

# 安装 compose arm 版本
install_docker_compose_arm(){
  print_info "$OS $ARCH docker-compose v$LNMP_DOCKER_COMPOSE_VERSION is installing by pip3 ...\n"
  command -v pip3 >/dev/null 2>&1 || sudo apt install -y python3-pip
  if ! [ -d ~/.pip ];then
    mkdir -p ~/.pip; echo -e "[global]\nindex-url = https://pypi.douban.com/simple\n[list]\nformat=columns" \
        > ~/.pip/pip.conf
  fi
  sudo pip3 install --upgrade docker-compose
}

install_docker_compose(){
  if ! [ "$OS" = 'Linux' ];then echo; print_error "Docker For Mac not Support install docker-compose"; exit 1; fi
  if [ "${ARCH}" = 'armv7l' ] || [ ${ARCH} = 'aarch64' ];then
    install_docker_compose_arm "$@"
  elif [ "$ARCH" = 'x86_64' ];then
    curl -sL ${COMPOSE_LINK}/${LNMP_DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` \
      > /tmp/docker-compose || print_error "Download docker-compose error, code is $?\n"
    install_docker_compose_move
  fi
}

docker_compose(){
  if [ "$1" = 'compose' ];then shift ; fi

  command -v docker-compose >/dev/null 2>&1 || local a=1

  if ! [ "$a" = 1 ];then
    # 存在
    # 取得版本号
    DOCKER_COMPOSE_VERSION=`docker-compose --version | cut -d ' ' -f 3 | cut -d , -f 1`
    local x=`echo $DOCKER_COMPOSE_VERSION | cut -d . -f 1`
    local y=`echo $DOCKER_COMPOSE_VERSION | cut -d . -f 2`
    #local z=`echo $DOCKER_COMPOSE_VERSION | cut -d . -f 3`
    local true_x=`echo $LNMP_DOCKER_COMPOSE_VERSION | cut -d . -f 1`
    local true_y=`echo $LNMP_DOCKER_COMPOSE_VERSION | cut -d . -f 2`
    #local true_z=`echo $LNMP_DOCKER_COMPOSE_VERSION | cut -d . -f 3`
    if [ "$x" != "$true_x" ];then exit 1; fi
    # 判断是否安装正确
    # -lt 小于
    if [ "$y" -lt "$true_y" ];then
      # 安装不正确
      if [ "$1" = '--official' ];then shift; print_info "Install compose from GitHub"; \
          install_docker_compose_official "$@"; return 0; fi
      if [ "$1" = '-f' ];then install_docker_compose -f; return 0; fi
      # 判断 OS
      if [ "$OS" = 'Darwin' ] ;then
        print_error \
"docker-compose v$DOCKER_COMPOSE_VERSION NOT installed Correct version, You MUST update Docker for Mac\n"
      exit
      elif [ "$OS" = 'Linux' ];then
        print_error \
"docker-compose v$DOCKER_COMPOSE_VERSION NOT installed Correct version, You MUST EXEC $ ./lnmp-docker compose -f\n"
      exit
      elif [ "$OS" = 'MINGW64_NT-10.0' ];then
        print_error \
"docker-compose v$DOCKER_COMPOSE_VERSION NOT installed Correct version, You MUST update Docker for Windows\n"
      exit
      else
        NOTSUPPORT
      fi
    # 安装正确
    else
      print_info "docker-compose v$DOCKER_COMPOSE_VERSION already installed Correct version\n"; return 0
    fi
  else
    # 不存在
    print_error "docker-compose NOT install, install...\n"
    if [[ "$1" = '--official' || "$2" = '--official' ]];then \
        shift; print_info "Install compose from GitHub"; install_docker_compose_official "$@" && return 0; fi
    install_docker_compose
  fi
}

network(){
  command -v ping > /dev/null 2>&1 || return
  ping -c 3 -W 3 baidu.com > /dev/null 2>&1 || ( print_error "Network connection error" ;exit 1)
}

# 克隆示例项目、nginx 配置文件
demo() {
  if [ -d config/nginx/.git ] || [ -f config/nginx/.git ];then
    echo > /dev/null 2>&1
  else
    print_info "Import app and nginx conf Demo ...\n"
    # 检查网络连接
    network
    # echo ;print_info "Update Git Submodule\n"
    # set +e
    # git submodule update --init --recursive
    # set -e
  fi
}

# 初始化
init() {
  docker volume create lnmp_composer_cache-data > /dev/null 2>&1 | echo > /dev/null

  case $APP_ENV in
    # 开发环境 拉取示例项目 [cn github]
    development )
      print_info "$APP_ENV\n"
      demo
      ;;

    # 生产环境 转移项目文件、配置文件、安装依赖包
    production )
      print_info "$APP_ENV\n"
      # 请在 ./scripts/production-init 定义要执行的操作
      scripts/production-init
      ;;
  esac
  # 初始化完成提示
  print_info "Init is SUCCESS\n"
}

# 更新项目

set_git_remote_origin_url(){
  network
  git remote get-url origin > /dev/null 2>&1 || local a=1
  if [ "$a" = 1 ];then
    # 不存在
    print_error "This git remote origin NOT set, seting...\n"
    git remote add origin git@github.com:khs1994-docker/lnmp.git
    # 不能使用 SSH
    git fetch --depth=1 origin > /dev/null 2>&1 || git remote set-url origin https://github.com/khs1994-docker/lnmp
    print_info `git remote get-url origin`
    echo
  elif [ `git remote get-url origin` != 'git@github.com:khs1994-docker/lnmp.git' ] \
      && [ `git remote get-url origin` != 'https://gitee.com/khs1994-docker/lnmp' ] \
      && [ `git remote get-url origin` != 'git@gitee.com:khs1994-docker/lnmp' ] \
      && [ `git remote get-url origin` != 'https://github.com/khs1994-docker/lnmp' ];then
    # 存在但是设置错误
    GIT_REMOTE_ORIGIN=`git remote get-url origin`
    print_error "This git remote origin ${GIT_REMOTE_ORIGIN} NOT set Correct, reseting...\n"
    git remote rm origin
    git remote add origin git@github.com:khs1994-docker/lnmp.git
    # 不能使用 SSH
    git fetch --depth=1 origin > /dev/null 2>&1 || git remote set-url origin https://github.com/khs1994-docker/lnmp
    print_info `git remote get-url origin`
  fi
}

update(){
  if ! [ -d .git ];then git init > /dev/null 2>&1; BRANCH=master; fi

  set_git_remote_origin_url

  for force in "$@"
  do
    if [ "$force" = '-f' ];then force='true'; fi
  done

  GIT_STATUS=`git status -s --ignore-submodules`
  if [ ! -z "${GIT_STATUS}" ] && [ ! "$force" = 'true' ];then
     git status -s --ignore-submodules
     echo; print_error "Please commit then update"
     exit 1
  fi
  git fetch --depth=1 origin
  print_info "Branch is ${BRANCH}\n"
  git reset --hard origin/${BRANCH}
  # echo ;print_info "Update Git Submodule\n"
  # set +e
  # git submodule update --init --recursive
  # set -e
  command -v bash > /dev/null 2>&1 || sed -i 's!^#\!/bin/bash.*!#\!/bin/sh!g' lnmp-docker
}

cn_mirror(){
  set -x
  set_git_remote_origin_url
  git remote add origin git@github.com:khs1994-docker/lnmp.git > /dev/null 2>&1 || echo > /dev/null
  git remote add aliyun git@code.aliyun.com:khs1994-docker/lnmp.git > /dev/null 2>&1 || echo > /dev/null
  git remote add tgit git@git.qcloud.com:khs1994-docker/lnmp.git > /dev/null 2>&1 || echo > /dev/null
  git remote add coding git@git.coding.net:khs1994/lnmp.git > /dev/null 2>&1 || echo > /dev/null
  git fetch origin
  git push -f aliyun remotes/origin/18.06:18.06
  git push -f aliyun remotes/origin/master:master
  git push -f aliyun --tags
  git push -f tgit remotes/origin/18.06:18.06
  git push -f tgit remotes/origin/master:master
  git push -f tgit --tags
  git push -f coding remotes/origin/18.06:18.06
  git push -f coding remotes/origin/master:master
  git push -f coding --tags
}

_lnmp_debug(){
  docker_version=$(docker --version)
  compose_version=$(docker-compose --version)
  git_commit=$(git log -1 --pretty=%H)
  echo "
<details>
<summary>OS Environment Info</summary>
<pre>
" > debug.md

cat /etc/os-release >> debug.md || uname -s >> debug.md

echo "
</pre>

<code>$docker_version</code>

<code>$compose_version</code>

* https://github.com/khs1994-docker/lnmp/commit/$git_commit

</details>
<details>
<summary>Console output</summary>

<!--Don't Edit it-->
<!--不要手动编辑以上内容,将终端输出内容贴到下面-->

<pre>









</pre>

</details>

## My Issue is

<!--在这里描述你的问题-->

XXX

XXX





<!--提交问题之前务必点击预览（Preview）标签-->
" >> debug.md

  echo "Please Edit debug.md, then new issue in https://github.com/khs1994-docker/lnmp/issues/new/choose with copy debug.md"

}

nginx_http(){

  echo "#
# Generate nginx config By khs1994-docker/lnmp
#

server {
  listen        80;
  server_name   $1;
  root          ${LNMP_PHP_PATH:-/app}/$2;
  index         index.html index.htm index.php;

  # include conf.d/demo-include-php.config

  location / {
    try_files \$uri \$uri/ /index.php?\$query_string;
  }

  location ~ .*\.php(\/.*)*$ {
    fastcgi_pass   php7:9000;
    include        fastcgi.conf;
  }
}" > config/${LNMP_NGINX_CONF_D:-nginx}/$1.conf

}

apache_http(){
  echo "#
# Generate Apache2 connfig By khs1994-docker/lnmp
#

<VirtualHost *:80>
  DocumentRoot \"${LNMP_PHP_PATH:-/app}/$2\"
  ServerName $1
  ServerAlias $1

  ErrorLog \"logs/$1.error.log\"
  CustomLog \"logs/$1.access.log\" common

  <FilesMatch \.php$>
    SetHandler \"proxy:fcgi://php7:9000\"
  </FilesMatch>

  <Directory \"/app/$2\" >
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>

</VirtualHost>" >> config/${LNMP_HTTPD_CONF_D:-httpd}/$1.conf
}

apache_https(){
  echo "#
# Generate Apache2 HTTPS config By khs1994-docker/lnmp
#

<VirtualHost *:443>
  DocumentRoot \"${LNMP_PHP_PATH:-/app}/$2\"
  ServerName $1
  ServerAlias $1

  ErrorLog \"logs/$1.error.log\"
  CustomLog \"logs/$1.access.log\" common

  SSLEngine on
  SSLCertificateFile conf/ssl/$1.crt
  SSLCertificateKeyFile conf/ssl/$1.key

  # HSTS (mod_headers is required) (15768000 seconds = 6 months)
  Header always set Strict-Transport-Security \"max-age=15768000\"

  <FilesMatch \.php$>
    SetHandler \"proxy:fcgi://php7:9000\"
  </FilesMatch>

  <Directory \"/app/$2\" >
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>

</VirtualHost>" >> config/${LNMP_HTTPD_CONF_D:-httpd}/$1.conf
}

nginx_https(){

  echo "#
# Generate nginx HTTPS config By khs1994-docker/lnmp
#

server {
  listen                    80;
  server_name               $1;
  return 301                https://\$host\$request_uri;
}

server{
  listen                     443 ssl http2;
  server_name                $1;
  root                       ${LNMP_PHP_PATH:-/app}/$2;
  index                      index.html index.htm index.php;

  # include conf.d/demo-include-ssl.config

  ssl_certificate            conf.d/ssl/$1.crt;
  ssl_certificate_key        conf.d/ssl/$1.key;

  ssl_session_cache          shared:SSL:1m;
  ssl_session_timeout        5m;
  ssl_protocols              TLSv1.2 TLSv1.3;
  ssl_ciphers                'TLS13+AESGCM+AES128:TLS13+AESGCM+AES256:TLS13+CHACHA20:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
  ssl_prefer_server_ciphers  on;

  ssl_stapling               on;
  ssl_stapling_verify        on;

  # include conf.d/demo-include-php.config

  location / {
    try_files \$uri \$uri/ /index.php?\$query_string;
  }

  location ~ .*\.php(\/.*)*$ {
    fastcgi_pass   php7:9000;
    include        fastcgi.conf;
  }
}" > config/${LNMP_NGINX_CONF_D:-nginx}/$1.conf

}

# 申请 ssl 证书
acme(){
  exec docker run --init -it --rm \
         -v $PWD/config/${LNMP_NGINX_CONF_D:-nginx}/ssl:/ssl \
         --mount source=lnmp_ssl-data,target=/acme.sh \
         --env-file .env \
         khs1994/acme:${ACME_VERSION} acme.sh "$@"
}

ssl(){
  if [ -z "$1" ];then
    exec echo "command example

$ ./lnmp-docker ssl khs1994.com [--rsa] [--httpd] [--debug] [acme other parameters]

通配符证书

$ ./lnmp-docker ssl khs1994.com -d *.khs1994.com -d *.t.khs1994.com

RSA 证书（默认 ECC 证书）

$ ./lnmp-docker ssl khs1994.com -d *.khs1994.com --rsa [--httpd] [--debug] [acme other parameters]

HTTPD server

$ ./lnmp-docker ssl khs1994.com -d *.khs1994.com --httpd [--rsa] [--debug] [acme other parameters]

ACME.sh help

$ ./lnmp-docker acme.sh
"
  fi

  for httpd in "$@"
  do
    if [ "${httpd}" = '--httpd' ];then
      HTTPD=1
    fi
    if [ "${httpd}" = '--rsa' ];then
      RSA=1
    fi
  done

  command="$@"
  command=${command[@]//'--rsa'/}
  command=${command[@]//'--httpd'/}

  exec docker run --init -it --rm \
         -v $PWD/config/$(if [ "$HTTPD" = 1 ];then \
             echo ${LNMP_HTTPD_CONF_D:-httpd}; else echo ${LNMP_NGINX_CONF_D:-nginx}; fi)/ssl:/ssl \
         --mount source=lnmp_ssl-data,target=/acme.sh \
         --env-file .env \
         -e HTTPD=${HTTPD:-0} \
         -e RSA=${RSA:-0} \
         khs1994/acme:${ACME_VERSION} "$command"
}

ssl_self(){
  docker run --init -it --rm -v $PWD/config/${LNMP_NGINX_CONF_D:-nginx}/ssl:/ssl khs1994/tls "$@"
}

# 快捷开始 PHP 项目开发

new(){
  for arg in "$@"; do if [ $arg = '-f' ];then rm -rf ${APP_ROOT}/$1; fi; done

  if [ -z "$1" ];then read -p "Please input project name: /app/" name; else name=$1; fi

  if [ -z "$name" ];then echo; print_error 'Please input content'; exit 1; fi

  if [ -d ${APP_ROOT}/$name ];then print_error "This folder existing"; exit 1; fi

  if [ -z "$2" -o "$2" = '-f' ];then read -p \
      "Please input domain:{ example http[s]://$name.domain.com }" input_url; else input_url=$2; fi

  if [ -z "$input_url" ]; then echo; print_error 'Please input content'; exit 1; fi

  protocol=$(echo $input_url | awk -F':' '{print $1}')

  url=$(echo $input_url | awk -F'[/:]' '{print $4}')

  if [ -z $url ];then url=$input_url; protocol=http; fi

  echo; print_info "PROTOCOL IS $protocol\n"

  print_info "URL IS $protocol://$url\n"

  if [ $protocol = 'https' ];then
    # 申请 ssl 证书
    read -n 1 -p "Self-Signed SSL certificate? [y/N]:" self_signed
    if [ "$self_signed" = 'y' ];then
      ssl_self $url
    else
      ssl $url
    fi
    # 生成 nginx 配置文件
    nginx_https $url $name
  else
    nginx_http $url $name
  fi

  mkdir -p ${APP_ROOT}/$name

  print_info "Now you can start PHP project in /${APP_ROOT}/$name\n"
  print_info "Please set hosts in /etc/hosts in development\n"
}

#
# $1 compose name
# $2 Swarm mode name
# $3 bash or sh
#

get_service_container_id(){
  local SERVICE_NAME=$1

  container_id=`docker container ls \
      --format "{{.ID}}" \
      -f label=${LNMP_DOMAIN:-com.khs1994.lnmp} \
      -f label=com.docker.compose.service=$SERVICE_NAME -n 1`

  if [ -z "$container_id" ];then
    container_id=`docker container ls \
        --format "{{.ID}}" \
        -f label=${LNMP_DOMAIN:-com.khs1994.lnmp} \
        -f label=com.docker.swarm.service.name=${COMPOSE_PROJECT_NAME:-lnmp}_$SERVICE_NAME -n 1`
  fi

  if [ -z "$container_id" ];then print_error "This Service No Container Running"; exit ; fi
}

bash_cli(){
  run_docker
  local SERVICE_NAME=$1
  get_service_container_id $SERVICE_NAME
  shift
  # avoid systemd error the input device is not a TTY
  docker exec -it $container_id $@ || docker exec -i $container_id $@
  exit $?
}

get_clusterkit_service_container_id(){
  local ENV_NAME=$1
  local SERVICE_NAME=$2

  container_id=`docker container ls \
      --format "{{.ID}}" \
      --filter \
      label=${LNMP_DOMAIN:-com.khs1994.lnmp} \
      --filter label=${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=$ENV_NAME \
      --filter label=com.docker.compose.service=$SERVICE_NAME -n 1`

  if [ -z "$container_id" ];then
    container_id=`docker container ls \
        --format "{{.ID}}" \
        --filter \
        label=${LNMP_DOMAIN:-com.khs1994.lnmp} \
        --filter label=${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=$ENV_NAME \
        --filter label=com.docker.swarm.service.name=${COMPOSE_PROJECT_NAME:-lnmp}_$SERVICE_NAME -n 1`
  fi

  if [ -z "$container_id" ];then print_error "This Service No Container Running"; exit; fi
}

clusterkit_bash_cli(){
  local ENV_NAME=$1
  local SERVICE_NAME=$2
  get_clusterkit_service_container_id $ENV_NAME $SERVICE_NAME
  shift 2
  docker exec -it $container_id $@ || docker exec -i $container_id $@

  exit $?
}

# 备份数据库

backup(){
  bash_cli mysql /backup/backup.sh $@
}

# 恢复数据库

restore(){
  bash_cli mysql /backup/restore.sh $1
}

pcit_nginx_init(){
  # 判断 nginx 配置文件是否存在

  if ! [ -f pcit/conf/pcit.conf ];then
    sudo cp pcit/conf/pcit.config pcit/conf/pcit.conf
  fi

  cat pcit/conf/pcit.conf | grep demo.ci.khs1994.com > /dev/null 2>&1 && print_error "PCIT conf error, please see pcit/README.md\n"

  # SSL 证书

  if ! [ -f pcit/ssl/ci.crt ];then
    print_error "PCIT Website SSL key not found, please see pcit/README.md"
    exit 1
  fi

  sudo cp pcit/ssl/ci.crt config/${LNMP_NGINX_CONF_D:-nginx}/ssl/ci.crt

  sudo cp pcit/conf/pcit.conf config/${LNMP_NGINX_CONF_D:-nginx}/pcit.conf
}

pcit_init(){
  # 判断 app/pcit 是否存在

  rm -rf ${APP_ROOT:-app}/.pcit
  # git clone --depth=1 https://github.com/pcit-ce/pcit ${APP_ROOT}/.pcit
  docker run -dit --name pcit_cp khs1994/pcit:alpine bash > /dev/null 2>&1
  docker cp pcit_cp:/app/pcit ${APP_ROOT:-app}/.pcit/
  docker rm -f pcit_cp > /dev/null 2>&1

  if ! [ -f pcit/.env.${APP_ENV:-development} ];then
    cp pcit/.env.example pcit/.env.${APP_ENV:-development}
  fi

  # if ! [ -f ${APP_ROOT}/pcit/public/.env.development ];then
  #   cp ${APP_ROOT}/pcit/public/.env.example ${APP_ROOT}/pcit/public/.env.development
  # fi

  # GitHub App private key

  if ! [ -f pcit/key/private.key ];then
    print_error "PCIT GitHub App private key not found, please see pcit/README.md"
    exit 1
  fi

  if ! [ -f pcit/key/public.key ];then
    docker run -it --rm -v $PWD/pcit/key:/app khs1994/pcit:alpine \
      openssl rsa -in private.key -pubout -out public.key
  fi

  sudo cp pcit/key/*.key ${APP_ROOT:-app}/.pcit/framework/storage/private_key/

  # env file

  sudo cp pcit/.env.* ${APP_ROOT:-app}/.pcit

  # 启动
}


# 入口文件

main() {
  logs
  local command=$1; shift
  case $command in
  acme.sh )
    run_docker; acme "$@"
    ;;

  init )
    init
    ;;

  backup )
    run_docker; backup "$@"
    ;;

  config )
    exec docker-compose -f docker-compose.yml \
      -f docker-compose.override.yml \
      -f docker-compose.include.yml \
      config
    ;;

  demo )
    demo
    ;;

  cleanup )
    cleanup
    ;;

  test )
    run_docker; cli/test
    ;;

  completion )
    ROOT_PATH=$HOME/.config/fish/completions
    if ! [ -d $ROOT_PATH ];then mkdir -p $ROOT_PATH ; fi
    ln -sf $PWD/cli/completion/fish/* $ROOT_PATH
    ls -la $ROOT_PATH
    ;;

  daemon-tls )
    echo
    echo https://github.com/khs1994-website/docs/blob/master/docker/dockerd.md
    echo
  ;;

  daemon-tls-cert )

  ;;

  debug )

  _lnmp_debug

  ;;

  gcr.io )
   cat /etc/hosts | grep 'gcr.io' > /dev/null || \
       (print_info "Append hosts, please input password " ; echo '127.0.0.1 k8s.gcr.io gcr.io' | sudo tee -a /etc/hosts )

   if ! [ "$OS" = 'Darwin' ];then
     sudo mkdir -p /etc/docker/certs.d/gcr.io
     sudo mkdir -p /etc/docker/certs.d/k8s.gcr.io
     sudo bash -c "cat config/registry/ca.crt > /etc/docker/certs.d/gcr.io/ca.crt"
     sudo bash -c "cat config/registry/ca.crt > /etc/docker/certs.d/k8s.gcr.io/ca.crt"
   fi

   _gcr_io "$@"
  ;;

  registry-up )
    _registry
    ;;

  registry-down )
    _registry_down
    ;;

  swarm-config )
    init; exec docker-compose -f ${PRODUCTION_COMPOSE_FILE} config
    ;;

  swarm-pull )
    run_docker
    # 仅允许运行在 Linux x86_64
    if [ "$OS" = 'Linux' ] && [ ${ARCH} = 'x86_64' ];then
      init; sleep 2; exec docker-compose -f ${PRODUCTION_COMPOSE_FILE} pull "$@"
    else
      print_error "Production NOT Support ${OS} ${ARCH}\n"
    fi
    ;;

  swarm-build )
    docker-compose -f ${PRODUCTION_COMPOSE_FILE} build "$@"
    ;;

  swarm-push )
    docker-compose -f ${PRODUCTION_COMPOSE_FILE} push "$@"
    ;;

  swarm-deploy )
    if [ "$OS" = 'Linux' ] && [ ${ARCH} = 'x86_64' ];then
      run_docker
      rm -rf app/.pcit
      pcit_init
      docker stack deploy -c ${PRODUCTION_COMPOSE_FILE} lnmp

      sleep 2; docker stack ps lnmp

    else
      print_error "Production NOT Support ${OS} ${ARCH}\n"
    fi
    ;;

  swarm-down )
    docker stack rm lnmp
    sleep 6
    ;;

  swarm-ps )
    docker stack ps lnmp
    ;;

  swarm-update )
  echo -e "
Example:


$ docker config create nginx_khs1994_com_conf_v2 config/${LNMP_NGINX_CONF_D:-nginx}/khs1994.com.conf

$ docker service update \\
    --config-rm nginx_khs1994_com_conf \\
    --config-add source=nginx_khs1994_com_conf_v2,target=/etc/nginx/conf.d/khs1994.com.conf \\
    lnmp_nginx

$ docker secret create khs1994_com_ssl_crt_v2 config/${LNMP_NGINX_CONF_D:-nginx}/ssl/khs1994.com.crt

$ docker service update \\
    --secret-rm khs1994_com_ssl_crt \\
    --secret-add source=khs1994_com_ssl_crt_v2,target=/etc/nginx/conf.d/ssl/khs1994.com.crt \\
    lnmp_nginx

$ docker service update --image nginx:1.13.10 lnmp_nginx

For information please run $ docker service update --help
"
  ;;

  satis )
    _satis

  ;;

  build )
    run_docker
    init

    if [ ${ARCH} = 'x86_64' ];then
      exec docker-compose -f docker-compose.yml -f docker-compose.build.yml build "$@"
    else
      NOTSUPPORT
    fi

    ;;

  build-up )
    run_docker
    init

    if [ ${ARCH} = 'x86_64' ];then
      exec docker-compose -f docker-compose.yml -f docker-compose.build.yml up -d "$@"
    else
      NOTSUPPORT
    fi

    ;;

  up )
    run_docker
    init
    # 判断架构
    if [ "$1" != '--systemd' ];then opt='-d'; else opt= ;fi
    if [ ${ARCH} = 'x86_64' ];then
      docker-compose \
        -f docker-compose.yml \
        -f docker-compose.override.yml \
        -f docker-compose.include.yml \
      up $opt ${LNMP_INCLUDE:-nginx mysql php7 redis phpmyadmin}
      echo; sleep 1; print_info "Test nginx configuration file...\n"
      docker exec -it \
          $(docker container ls --format {{.ID}} \
          -f label=${LNMP_DOMAIN:-com.khs1994.lnmp} \
          -f label=com.docker.compose.service=nginx -n 1 ) nginx -t
    elif [ ${ARCH} = 'armv7l' -o ${ARCH} = 'aarch64' ];then
      docker-compose -f docker-arm.yml up $opt ${LNMP_INCLUDE:-nginx mysql php7 redis phpmyadmin}
      echo; sleep 1; print_info "Test nginx configuration file...\n"
      docker-compose -f docker-arm.yml exec nginx nginx -t || \
        (print_error "nginx configuration file test failed, You must check nginx configuration file!"; exit 1)

      echo; print_info "nginx configuration file test is successful\n" ; exit 0
    else
      NOTSUPPORT
    fi
    ;;

  build-config )
    init; if [ ${ARCH} = 'x86_64' ];then \
        exec docker-compose -f docker-compose.yml -f docker-compose.build.yml config; else NOTSUPPORT; fi
    ;;

  restore )
    run_docker; restore "$@"
    ;;

  update|upgrade )
    update "$@"
    ;;

  nginx-config )
     if [ -z "$3" ];then print_error "$ ./lnmp-docker nginx-config {https|http} {PATH} {URL}"; exit 1; fi
     print_info 'Please set hosts in /etc/hosts in development\n'
     print_info \
'Maybe you need generate nginx HTTPS conf in website \
https://khs1994-website.github.io/server-side-tls/ssl-config-generator/'
     if [ "$1" = 'http' ];then shift; nginx_http $2 $1; fi
     if [ "$1" = 'https' ];then shift; nginx_https $2 $1; fi
     echo
     print_info "You must checkout ./config/${LNMP_NGINX_CONF_D:-nginx}/$2.conf, then restart nginx $ lnmp-docker restart nginx"
     ;;

  httpd-config )
    if [ -z "$3" ];then print_error "$ ./lnmp-docker apache-config {https|http} {PATH} {URL}"; exit 1; fi
    print_info 'Please set hosts in /etc/hosts in development\n'
    print_info \
'Maybe you need generate Apache2 HTTPS conf in website \
https://khs1994-website.github.io/server-side-tls/ssl-config-generator/'
    if [ "$1" = 'http' ];then shift; apache_http $2 $1; fi
    if [ "$1" = 'https' ];then shift; apache_https $2 $1; fi
    echo
    print_info "You must checkout ./config/${LNMP_HTTPD_CONF_D:-httpd}/$2.conf, then restart httpd $ lnmp-docker restart httpd"
    ;;

  php-cli | php7-cli )
      local cli_command
      if [ -z "$1" ];then cli_command=bash; else cli_command="$@"; fi
      bash_cli php7 $cli_command
    ;;

  mongodb-cli | mongo-cli )
     local cli_command
     if [ -z "$1" ];then cli_command=bash; else cli_command="$@"; fi
    bash_cli mongodb $cli_command
    ;;

  mariadb-cli )
    local cli_command
    if [ -z "$1" ];then cli_command=bash; else cli_command="$@"; fi
    bash_cli mariadb $cli_command
    ;;

  mysql-cli )
    local cli_command
    if [ -z "$1" ];then cli_command=bash; else cli_command="$@"; fi
    bash_cli mysql $cli_command
    ;;

  nginx-unit-cli )
    local cli_command
    if [ -z "$1" ];then cli_command=bash; else cli_command="$@"; fi
    bash_cli nginx-unit $cli_command
    ;;

  *-cli )
    local SERVICE=$(echo $command | cut -d '-' -f 1)
    local cli_command
    if [ -z "$1" ];then cli_command=sh; else cli_command="$@"; fi
    run_docker
    bash_cli $SERVICE $cli_command
    ;;

  *-container-id )
    local SERVICE=$(echo $command | cut -d '-' -f 1)
    get_service_container_id $SERVICE
    echo $container_id
    ;;

  *-logs | *-log )

    if ! [ "${OS}" = 'Linux' ];then NOTSUPPORT; fi

    SERVICE=$(echo $command | cut -d '-' -f 1)
    journalctl -u \
    docker.service \
    CONTAINER_ID=$(docker container ls --format "{{.ID}}" \
                              -f label=${LNMP_DOMAIN:-com.khs1994.lnmp} \
                              -f label=com.docker.swarm.service.name=lnmp_${SERVICE} ) "$@"
    ;;

  build-push )
    run_docker; init; exec \
        docker-compose -f docker-compose.build.yml build && docker-compose -f docker-compose.build.yml push
    ;;

  down )
    init; docker-compose down --remove-orphans
    ;;

  docs )
    run_docker; gitbook
    ;;

  pull )
    run_docker; init
    case "${ARCH}" in
        x86_64 )
          sleep 2; exec docker-compose pull ${LNMP_INCLUDE:-nginx mysql php7 redis phpmyadmin}
          ;;
        aarch64 | armv7l )
          sleep 2; exec docker-compose -f docker-arm.yml pull ${LNMP_INCLUDE:-nginx mysql php7 redis phpmyadmin}
          ;;
        * )
          NOTSUPPORT
          ;;
    esac
     ;;

  cn-mirror )
    cn_mirror
    ;;

  cookbooks )

    _local_docs_server
  ;;

  compose )
    docker_compose "$@"
    ;;

  new )
    new "$@"
    ;;

  ssl )
    run_docker; ssl "$@"
    ;;

  ssl-self )
    if [ -z "$1" ];then
      print_error '$ ./lnmp-docker ssl-self {IP|DOMAIN}'
      echo -e "
Example:

$ ./lnmp-docker ssl-self khs1994.com 127.0.0.1 192.168.199.100 localhost ...

$ ./lnmp-docker ssl-self khs1994.com *.khs1994.com *.t.khs1994.com 127.0.0.1 ...
"
    exit 1
    fi
    ssl_self "$@"
    echo; print_info 'Please set hosts in /etc/hosts'
    ;;

  tests )
    print_info "Test Shell Script"
    exec echo
    ;;

  version )
    echo Docker-LNMP ${LNMP_DOCKER_VERSION}
    ;;

  -h | --help | help )
   help
   ;;

  clusterkit-help )
    clusterkit_help
    ;;

  restart )
    if [ -z "$1" ];then docker-compose down --remove-orphans; \
        print_info "Please exec \n\n$ ./lnmp-docker up\n"; exit 0; fi

    for soft in "$@"
    do
      if [ $soft = 'nginx' ];then opt='true'; fi
    done

    if [ "$opt" = 'true' ];then
      docker exec -it $(docker container ls \
                            --format {{.ID}} \
                            -f label=${LNMP_DOMAIN:-com.khs1994.lnmp} \
                            -f label=com.docker.compose.service=nginx -n 1 ) nginx -t || \
        (echo; print_error "nginx configuration file test failed, You must check nginx configuration file!"; exit 1)

      echo; print_info "nginx configuration file test is successful\n"
      exec docker-compose $command "$@"
    else
      print_info "You Exec docker-compose commands"; echo
      exec docker-compose $command "$@"
    fi
    ;;

 daemon-socket )
   if [ $OS != 'Darwin' ];then NOTSUPPORT; fi
   docker run -d --restart=always \
     -p 2375:2375 \
     -v /var/run/docker.sock:/var/run/docker.sock \
     -e PORT=2375 \
     shipyard/docker-proxy
     ;;

  clusterkit )
     docker-compose -f docker-compose.yml \
       -f docker-compose.override.yml \
       -f cluster/docker-cluster.mysql.yml \
       -f cluster/docker-cluster.redis.yml \
       up "$@"
     ;;

  clusterkit-mysql-up )
     docker-compose --project-directory=$PWD -f cluster/docker-cluster.mysql.yml up "$@"
     ;;

  clusterkit-mysql-down )
     docker-compose --project-directory=$PWD -f cluster/docker-cluster.mysql.yml down "$@"
     ;;

  clusterkit-mysql-exec )

  if [ "$#" -lt 2 ];then
     print_error '$ ./lnmp-docker clusterkit-mysql-exec {master|node-N} {COMMAND}' ; exit 1
  fi

     NODE=$1
     shift
     COMMAND=$@

       clusterkit_bash_cli clusterkit_mysql mysql_$NODE ${COMMAND:-bash}
     ;;

  clusterkit-mysql-deploy )
       cp cluster/docker-cluster.mysql.yml docker-cluster.mysql.yml
       docker stack deploy -c docker-cluster.mysql.yml mysql_cluster
        ;;

  clusterkit-mysql-remove )
       docker stack rm mysql_cluster
        ;;

  clusterkit-memcached-up )
    docker-compose --project-directory=$PWD -f cluster/docker-cluster.memcached.yml up "$@"
    ;;

  clusterkit-memcached-down )
    docker-compose --project-directory=$PWD -f cluster/docker-cluster.memcached.yml down "$@"
    ;;

  clusterkit-memcached-exec )

  if [ "$#" -lt 2 ];then
     print_error '$ ./lnmp-docker clusterkit-memcached-exec {N} {COMMAND}' ; exit 1
  fi

    NODE=$1
    shift
    COMMAND=$@

    clusterkit_bash_cli clusterkit_memcached memcached-$NODE ${COMMAND:-bash}
    ;;

  clusterkit-memcached-deploy )
    cp cluster/docker-cluster.memcached.yml docker-cluster.memcached.yml
    docker stack deploy -c docker-cluster.memcached.yml memcached_cluster
    ;;

  clusterkit-memcached-remove )
    docker stack rm memcached_cluster
    ;;

  clusterkit-redis-up )
        if [ -z "$CLUSTERKIT_REDIS_HOST" ];then print_error "You must set CLUSTERKIT_REDIS_HOST in .env file" ; exit 1 ; fi
        docker-compose --project-directory=$PWD -f cluster/docker-cluster.redis.yml up "$@"
        ;;

  clusterkit-redis-down )
        docker-compose --project-directory=$PWD -f cluster/docker-cluster.redis.yml down "$@"
        ;;

  clusterkit-redis-exec )

  if [ "$#" -lt 2 ];then
     print_error '$ ./lnmp-docker clusterkit-redis-exec {master-N|slave-N} {COMMAND}' ; exit 1
  fi
        NODE=$1
        shift
        COMMAND=$@

          clusterkit_bash_cli clusterkit_redis redis_$NODE ${COMMAND:-bash}
        ;;

  clusterkit-redis-deploy )
    cp cluster/docker-cluster.redis.yml docker-cluster.redis.yml
    docker stack deploy -c docker-cluster.redis.yml redis_cluster
    ;;

  clusterkit-redis-remove )
    docker stack rm redis_cluster
    ;;

  clusterkit-redis-replication-up )
        if [ -z "$CLUSTERKIT_REDIS_M_S_HOST" ];then print_error "You must set CLUSTERKIT_REDIS_M_S_HOST in .env file" ; exit 1 ; fi
        docker-compose --project-directory=$PWD -f cluster/docker-cluster.redis.replication.yml up "$@"
        ;;

  clusterkit-redis-replication-down )
        docker-compose --project-directory=$PWD -f cluster/docker-cluster.redis.replication.yml down "$@"
        ;;

  clusterkit-redis-replication-exec )
    if [ "$#" -lt 2 ];then \
       print_error \
       '$ ./lnmp-docker clusterkit-redis-replication-exec {master | slave-N} {COMMAND}' ; exit 1 ; fi

        NODE="$1"
        shift
        COMMAND="$@"
        clusterkit_bash_cli clusterkit_redis_replication redis_m_s_$NODE ${COMMAND:-bash}
        ;;

  clusterkit-redis-replication-deploy )
    cp cluster/docker-cluster.redis.replication.yml docker-cluster.redis.replication.yml
    docker stack deploy -c docker-cluster.redis.replication.yml redis_m_s_cluster
    ;;

  clusterkit-redis-replication-remove )
    docker stack rm redis_m_s_cluster
    ;;

  clusterkit-redis-sentinel-up )
        if [ -z "$CLUSTERKIT_REDIS_S_HOST" ];then print_error "You must set CLUSTERKIT_REDIS_S_HOST in .env file" ; exit 1 ; fi
        docker-compose --project-directory=$PWD -f cluster/docker-cluster.redis.sentinel.yml up "$@"
        ;;

  clusterkit-redis-sentinel-down )
        docker-compose --project-directory=$PWD -f cluster/docker-cluster.redis.sentinel.yml down "$@"
        ;;

  clusterkit-redis-sentinel-exec )
  if [ "$#" -lt 2 ];then \
      print_error \
        '$ ./lnmp-docker clusterkit-redis-sentinel-exec {master-N|slave-N|sentinel-N} {COMMAND}' ; exit 1 ; fi

        NODE=$1
        shift
        COMMAND=$@
          clusterkit_bash_cli clusterkit_redis_sentinel redis_sentinel_$NODE ${COMMAND:-bash}
        ;;

  clusterkit-redis-sentinel-deploy )
    cp cluster/docker-cluster.redis.sentinel.yml docker-cluster.redis.sentinel.yml
    docker stack deploy -c docker-cluster.redis.sentinel.yml redis_s_cluster
    ;;

  clusterkit-redis-sentinel-remove )
    docker stack rm redis_s_cluster
    ;;

  clusterkit-* )
        command=$(echo $command | cut -d '-' -f 2)
        exec docker-compose -f docker-compose.yml \
             -f docker-compose.override.yml \
             -f cluster/docker-cluster.mysql.yml \
             -f cluster/docker-cluster.redis.yml \
             $command "$@"
        ;;

  swarm-clusterkit )
    cp cluster/docker-cluster.mysql.yml docker-cluster.mysql.yml
    docker stack deploy -c docker-production.yml -c docker-cluster.mysql.yml lnmp
        ;;

  dashboard )
    echo -e "
$ cd kubernetes

$ kubectl apply -f coreos/addons/dashboard.yaml

$ kubectl proxy

OPEN http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

First Run? Maybe you wait 60s then open url.
"
    print_info "More information please see https://github.com/kubernetes/dashboard"

    ;;

    update-version )
        update_version
    ;;

    pcit-cp )
      docker pull khs1994/pcit:alpine
      pcit_init
    ;;

    pcit-up )
    pcit_init
    pcit_nginx_init

    if [ -z "$1" ];then
    docker-compose -f docker-compose.yml -f docker-compose.override.yml \
        -f docker-compose.include.yml -f docker-pcit.include.yml up -d \
        ${LNMP_INCLUDE} pcit
    fi
    ;;

    nfs )
    sudo modprobe {nfs,nfsd,rpcsec_gss_krb5}
    sudo modprobe nfsd
    cd volumes
    if [ "$1" = 'down' ];then
      docker-compose stop nfs

      exit
    fi
    docker-compose up -d nfs

    ;;

    checkout )
      if [ -z "${DOCKER_VERSION_YY}" ];then print_error "check Docker version error"; exit; fi

      git fetch origin ${DOCKER_VERSION_YY}.${DOCKER_VERSION_MM}:${DOCKER_VERSION_YY}.${DOCKER_VERSION_MM} || echo > /dev/null
      git checkout ${DOCKER_VERSION_YY}.${DOCKER_VERSION_MM}
      update
      ;;

      alipay )
        clear
        cat ad/alipay.txt

        echo "
1. 打开支付宝扫一扫

2. 扫描二维码领取红包

3. 线下扫码支付
        "
      ;;

      haokan )
        clear
        cat ad/haokan.txt

        echo "
1. 扫描二维码，输入手机号领取红包

2. 下载好看视频，输入手机号登录

3. 观看视频
        "
      ;;

  * )
  if ! [ -z "$command" ];then
    print_warning "command not found, Now Exec docker-compose commands"; echo
    exec docker-compose $command "$@"
  fi
  help
    ;;
  esac
}

if [ "$debug" = 'true' ];then set -x; fi

# if docker version info not include ce, example 1.13.1, maybe install method is error

ARCH=`uname -m` && OS=`uname -s`

COMPOSE_LINK_OFFICIAL=https://github.com/docker/compose/releases/download

COMPOSE_LINK=https://code.aliyun.com/khs1994-docker/compose-cn-mirror/raw

# 获取正确版本号

env_status && . ./.env && . cli/.env

APP_ROOT=$(cd ${APP_ROOT:-./app}; pwd)

print_info "APP_ROOT is $APP_ROOT\n"

check_nginx_conf

if [ -d .git ];then
  BRANCH=`git rev-parse --abbrev-ref HEAD`
  print_info "Branch is ${BRANCH}\n"
fi

_check_docker_version(){
  if [ -z "${BRANCH}" ];then
    return
  fi

  DOCKER_VERSION_YY=$(docker -v | cut -d ' ' -f 3 | cut -d '.' -f 1)
  DOCKER_VERSION_MM=$(docker -v | cut -d ' ' -f 3 | cut -d '.' -f 2)

  if [ "${DOCKER_VERSION_YY}.${DOCKER_VERSION_MM}" != "${BRANCH}" ];then
    print_warning "Current branch incompatible with your docker version, please checkout ${DOCKER_VERSION_YY}.${DOCKER_VERSION_MM} branch by exec $ ./lnmp-docker checkout\n"
  fi
}

command -v docker > /dev/null 2>&1 && _check_docker_version

# 写入版本号

if [ ${OS} = "Darwin" ];then
  sed -i "" "s/^LNMP_DOCKER_VERSION.*/LNMP_DOCKER_VERSION=${LNMP_DOCKER_VERSION}/g" .env
else
  sed -i "s/^LNMP_DOCKER_VERSION.*/LNMP_DOCKER_VERSION=${LNMP_DOCKER_VERSION}/g" .env
fi

if [ ${ARCH} = 'armv7l' ];then
    sed -i "s/^ARM_ARCH.*/ARM_ARCH=arm32v7/g" .env
    sed -i "s/^ARM_PHP_BASED_OS.*/ARM_PHP_BASED_OS=stretch/g" .env
    sed -i "s/^ARM_BASED_OS.*/ARM_BASED_OS=/g" .env
elif [ ${ARCH} = 'aarch64' ];then
    sed -i "s/^ARM_ARCH.*/ARM_ARCH=arm64v8/g" .env
    sed -i "s/^ARM_PHP_BASED_OS.*/ARM_PHP_BASED_OS=alpine/g" .env
fi

print_info "ARCH is ${OS} ${ARCH}\n"

command -v docker > /dev/null 2>&1 && print_info `docker --version` || print_warning "docker cli is not install"

echo ; docker_compose "$@"

# data collaction

if ! [ "${DATA_COLLECTION}" = "false" ];then _tongji; fi

# output help

if [ $# = 0 ];then help; exit 0; fi

# 生产环境 compose 文件

PRODUCTION_COMPOSE_FILE='docker-production.yml'

set +e

ls docker-production.*.yml > /dev/null 2>&1

if [ $? = '0' ];then PRODUCTION_COMPOSE_FILE=`ls docker-production.*.yml`; fi

set -e

main "$@"
