pipeline {
  agent any
  environment {
    PLATFORM = "linux/amd64,linux/arm64,linux/arm/v7"
    DOCKER_PASSWORD = "${env.DOCKER_PASSWORD}"
    TENCENT_DOCKER_USERNAME = "${env.TENCENT_DOCKER_USERNAM}"
    DOCKER_CLI_EXPERIMENTAL = "enabled"
    BUILDX_IMAGE= "dockerpracticesig/buildkit:master-tencent"
  }
  stages {
    stage("os-manifest"){
      steps {
        sh "cat /etc/os-release"
      }
    }

    stage('同步镜像') {
      steps {
        sh "curl -L -O https://gitee.com/khs1994-docker/lnmp/raw/19.03/dockerfile/php/docker-image-sync.json"

        sh "docker run -i --rm -e DEST_DOCKER_USERNAME=\${TENCENT_DOCKER_USERNAME} \
            -e DEST_DOCKER_PASSWORD=\${DOCKER_PASSWORD} \
            -e SOURCE_DOCKER_REGISTRY=mirror.ccs.tencentyun.com \
            -e CI=true \
            -v \$PWD/docker-image-sync.json:/root/lnmp/windows/docker-image-sync.json \
            khs1994/docker-image-sync"
      }
    }

  }
}
