services:
  memcached:
    build:
      << : *default-build
      # << : *default-build-debian
      context: ./dockerfile/memcached/
      dockerfile: Dockerfile
    # ports:
    #   - "127.0.0.1:11211:11211"
    volumes:
      - zoneinfo-data:/usr/share/zoneinfo
    deploy:
      << : *default-deploy
      << : *default-labels
      placement:
        constraints: [node.role == manager]
    # logging: *default-logging
