#!/bin/bash

if [ -f khs1994-robot.enc ];then echo -e "\n\033[32mINFO\033[0m Can't EXEC in cli folder"; exit 1; fi

. .env; COMPOSE_PATH="$1"; shift; CMD="$@"; ARCH=`uname -m`

# 判断架构

TAG=${KHS1994_LNMP_PHP_VERSION}-alpine3.7

if [ ${ARCH} = 'armv7l' ] || [ ${ARCH} = 'aarch64' ];then
  DOCKER_IMAGE=khs1994/arm64v8-php-fpm
  if [ ${ARCH} = 'armv7l' ];then
    DOCKER_IMAGE=khs1994/arm32v7-php-fpm
    TAG=${KHS1994_LNMP_PHP_VERSION}-stretch
  fi
elif [ ${ARCH} = 'x86_64' ];then
  docker image ls | grep ccr.ccs.tencentyun.com/khs1994/php-fpm > /dev/null 2>&1
  if [ "$?" = 0 ];then DOCKER_IMAGE=ccr.ccs.tencentyun.com/khs1994/php-fpm; else DOCKER_IMAGE=khs1994/php-fpm; fi
else
  echo -e "\n\033[32mINFO\033[0m  ${ARCH} 暂不支持"
  exit 1
fi

# if build image
# DOCKER_IMAGE=lnmp-php

echo -e  "\n\033[32mINFO\033[0m  在 ${DOCKER_IMAGE}:${TAG} 内 /app/${COMPOSE_PATH} 执行 $ composer ${CMD}" && echo -e  "\n\033[32mINFO\033[0m  以下为输出内容\n\n"

exec docker run -it --rm \
  -v $PWD/app/${COMPOSE_PATH}:/app \
  -v $PWD/tmp/cache:/tmp/cache \
  ${DOCKER_IMAGE}:${TAG} \
  composer ${CMD}
