#!/usr/bin/env bash

# WSL init

sudo sed -i "s#deb.debian.org#mirrors.ustc.edu.cn#g" /etc/apt/sources.list
sudo sed -i "s#security.debian.org#mirrors.ustc.edu.cn#g" /etc/apt/sources.list

sudo sed -i "s#archive.ubuntu.com#mirrors.ustc.edu.cn#g" /etc/apt/sources.list
sudo sed -i "s#security.ubuntu.com#mirrors.ustc.edu.cn#g" /etc/apt/sources.list

if [ -z "$APP_ENV" ];then echo "export APP_ENV=wsl" >> ~/.bashrc; fi

if [ -z "$WSL_HOME" ];then echo "export WSL_HOME=/c/Users/90621" >> ~/.bashrc; fi

if [ -z "$COMPOSER_HOME" ];then echo "export COMPOSER_HOME=/tmp" >> ~/.bashrc; fi

if [ -z "$DOCKER_BUILDKIT" ];then echo "export DOCKER_BUILDKIT=1" >> ~/.bashrc; fi

if [ -z "$DOCKER_CLI_EXPERIMENTAL" ];then echo "export DOCKER_CLI_EXPERIMENTAL=enabled" >> ~/.bashrc; fi

if [ -z "$DOCKER_HOST" ];then
  echo "export DOCKER_HOST=127.0.0.1:2375" >> ~/.bashrc
fi

# WSL2
if [ `uname -r` = '4.19.43-microsoft-standard' ];then

  if [ -z "$WSL2_WINDOWS_HOST" ];then
    echo "export WSL2_WINDOWS_HOST=\$(nslookup 127.0.0.1 | awk -F ":" '{print \$2}' | head -n 1 | sed \"s#\\t##g\")" >> ~/.bashrc;
  fi

  if [ -z "$DOCKER_HOST" ];then
    echo "export DOCKER_HOST=\${WSL2_WINDOWS_HOST}:2376" >> ~/.bashrc
  fi

fi

sudo apt update && sudo apt -y install \
                            bash-completion \
                            vim \
                            git \
                            curl \
                            wget \
                            lsb-release \
                            python \
                            python-pip \
                            python3 \
                            python3-pip \
                            openssh-server \
                            apt-file \
                            man \
                            dnsutils

# composer cn mirror

command -v /usr/local/bin/composer \
  && composer config -g repo.packagist composer https://php.cnpkg.org

# 命令行补全

if ! [ -d /etc/bash_completion.d ];then sudo mkdir -p /etc/bash_completion.d; fi

if ! [ -f /etc/bash_completion.d/docker ];then
sudo curl -L \
  https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker \
  -o /etc/bash_completion.d/docker
fi

# verify

docker --version

# cp docker desktop k8s config

mkdir -p ${HOME}/.kube

for user in `ls /c/Users`;
do
  if [ -f "/c/Users/${user}/.kube/config" ];then
    if ! [ -f "${HOME}/.kube/config" ];then
      cp "/c/Users/${user}/.kube/config" ${HOME}/.kube/config

      echo -e "\n\n==> copy .kube folder success\n\n"

      kubectl version
    fi
  fi
done

echo -e '\n';
