services:
  php7:
    volumes:
      # fpm config
      - ./config/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      # php.ini
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro
      # php.ini override
      - ./config/php/docker-php.ini:/usr/local/etc/php/conf.d/docker-php.ini:ro
      # log,etc
      - ./log/php:/var/log/php
      # supervisord
      - ./log/supervisord.log:/var/log/supervisord.log
      - ./log/supervisord:/var/log/supervisord
      # s6
      - ./config/s6/s6-overlay/scripts:/etc/s6-overlay/scripts
      - ./config/s6/s6-overlay/${S6_RC_D:-s6-rc.d}:/etc/s6-overlay/s6-rc.d
      - ./config/crontabs/root:/etc/crontabs/root.s6
    # command: php-fpm -R -F
    # command: php-fpm -F
    environment:
      - LNMP_XDEBUG_REMOTE_HOST=${LNMP_XDEBUG_REMOTE_HOST:-192.168.199.100}
      - LNMP_XDEBUG_REMOTE_PORT=${LNMP_XDEBUG_REMOTE_PORT:-9003}
      # - PHP_INI_SCAN_DIR=:/usr/local/etc/php/conf.d
