x-common-labels:
  &common-labels
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=${APP_ENV:-development}

x-common:
  &common
  restart: ${LNMP_RESTART:-always}
  env_file: ./scripts/cli/timezone.env
  networks:
    - backend
  read_only: ${LNMP_ROOT_FILESYSTEM_READ_ONLY:-false}
  # dns:
  #   - ${DNS:-114.114.114.114}

services:
  php7:
    &php7
    << : [*common,*common-labels]
    image: "${LNMP_DOCKER_IMAGE_PREFIX:-khs1994}/php:${LNMP_PHP7_VERSION:-7.4.33}-fpm-alpine"
    volumes:
      - &bind_app ${APP_ROOT:-./app}:${LNMP_PHP_PATH:-/app}
      - type: volume
        source: zoneinfo-data
        target: /usr/share/zoneinfo
        volume:
          nocopy: false
    networks:
      - frontend
      - backend
      # frontend:
      #   aliases:
      #   - php
      # backend:
      #   aliases:
      #   - php
    tmpfs: /run:exec
    expose:
      - "9000"
    environment:
      - &lnmp_version LNMP_VERSION=${LNMP_VERSION:-v24.11} x86_64 With Pull Docker Image
      - APP_ENV=${APP_ENV:-development}
      - LNMP_OPCACHE_ENABLE=${LNMP_OPCACHE_ENABLE:-1}
      - PATH=/command:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

  # https://docs.docker.com/config/containers/multi-service_container/
  # http://supervisord.org/running.html
  supervisord:
    << : *php7
    networks:
      - backend
    image: "${LNMP_DOCKER_IMAGE_PREFIX:-khs1994}/php:${LNMP_PHP_VERSION:-7.4.33}-supervisord-alpine"
    secrets:
      - source: supervisord_ini
        target: /etc/supervisor.d/supervisord.ini
    command: ["/usr/bin/supervisord","-n"]
    expose:
      - "9003"

volumes:
  php7-var-log:
    << : *common-labels

secrets:
  supervisord_ini:
    << : *common-labels
    file: ./config/supervisord/supervisord.ini
