name: crun
version: "1.24"
url: "https://github.com/containers/crun/releases/download/${VERSION}/crun-${VERSION}-${env:lwpm_os}-${env:lwpm_architecture}"
scripts:
  platform-reqs: if(!$IsLinux){echo $False}
  dist: |
    _mkdir $env:LWPM_PKG_ROOT/dist/${env:lwpm_os}-${env:lwpm_architecture}

    curl -L `
      $url `
      -o $env:LWPM_PKG_ROOT/dist/${env:lwpm_os}-${env:lwpm_architecture}/crun-${VERSION}-${env:lwpm_os}-${env:lwpm_architecture}

    curl -L `
      $url `
      -o $env:LWPM_PKG_ROOT/dist/${env:lwpm_os}-${env:lwpm_architecture}/crun-${VERSION}-${env:lwpm_os}-${env:lwpm_architecture}-disable-systemd

platform:
  - architecture: amd64
    os: linux
  - architecture: arm64
    os: linux
