#!/bin/bash

if [ $1 = 'rsa' ];then
  lnmp-docker.sh ssl khs1994.com -d *.khs1994.com \
                     -d *.developer.khs1994.com \
                     -d *.home.khs1994.com --rsa
fi

lnmp-docker.sh ssl khs1994.com -d *.khs1994.com \
                   -d *.developer.khs1994.com \
                   -d *.home.khs1994.com
