pipeline {
  agent any
  environment {
    PLATFORM = "linux/amd64,linux/arm64,linux/arm/v7"
    DOCKER_PASSWORD = "${env.DOCKER_PASSWORD}"
    TENCENT_DOCKER_USERNAME = "${env.TENCENT_DOCKER_USERNAM}"
    DOCKER_CLI_EXPERIMENTAL = "enabled"
    BUILDX_IMAGE = "dockerpracticesig/buildkit:master-tencent"
    // SOURCE_DOCKER_REGISTRY = "mirror.ccs.tencentyun.com"
    SOURCE_DOCKER_REGISTRY = "pcit-docker.pkg.coding.net"
    SOURCE_NAMESPACE = "khs1994-docker/khs1994"
    DEST_DOCKER_REGISTRY = "ccr.ccs.tencentyun.com"
    DEST_NAMESPACE = "khs1994"
  }
  stages {
    stage("os-manifest"){
      steps {
        sh "cat /etc/os-release"
      }
    }

    stage('同步镜像-tencent-cloud') {
      steps {
        sh "curl -L -O https://gitee.com/khs1994-docker/lnmp/raw/20.10/dockerfile/php/sync/docker-image-sync.json"

        sh '''
        docker run -i --rm \
            -e DEST_DOCKER_USERNAME=\${TENCENT_DOCKER_USERNAME} \
            -e DEST_DOCKER_PASSWORD=\${DOCKER_PASSWORD} \
            -e SOURCE_DOCKER_REGISTRY=\${SOURCE_DOCKER_REGISTRY} \
            -e DEST_DOCKER_REGISTRY=\${DEST_DOCKER_REGISTRY} \
            -e SOURCE_NAMESPACE=\${SOURCE_NAMESPACE} \
            -e DEST_NAMESPACE=\${DEST_NAMESPACE} \
            -e CI=true \
            -e DOCKER_TOKEN_EXPIRE_TIME=115 \
            -e CONFIG_URL=https://gitee.com/khs1994-docker/lnmp/raw/20.10/dockerfile/php/sync/docker-image-sync.json \
            -v \$PWD/docker-image-sync.json:/docker-entrypoint.d/docker-image-sync.json \
            pcit-docker.pkg.coding.net/khs1994-docker/khs1994/docker-image-sync
        '''
      }
    }

  }
}
