FROM php:7.2.1-fpm-alpine3.7

ENV TZ=Asia/Shanghai

# 替换源

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN apk add --no-cache libzip-dev \
    && docker-php-ext-configure zip \
                                --with-libzip= \
    && docker-php-ext-install -j "$(nproc)" zip
