#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

# change xdebug_remote_host

if ! [ "${APP_ENV}" = "production" ];then
if [ -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.temp ];then
  cp /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.temp \
    /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  sed -i "s#^xdebug.remote_host.*#xdebug.remote_host=${XDEBUG_REMOTE_HOST}#g" \
    /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
fi
fi

exec "$@"
