FROM php:7.2.1-fpm-alpine3.7

ENV TZ=Asia/Shanghai

ARG ALPINE_URL=dl-cdn.alpinelinux.org

RUN sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_URL}/g" /etc/apk/repositories \
    && apk add --no-cache libzip-dev \
    && docker-php-ext-configure zip \
                                --with-libzip= \
    && docker-php-ext-install -j "$(nproc)" zip
