# syntax=docker/dockerfile:labs

FROM --platform=$TARGETPLATFORM alpine

RUN --mount=type=bind,from=khs1994/s6:3.1.0.1,source=/,target=/tmp/s6 \
    set -x \
    && tar -xvf /tmp/s6/s6-overlay-noarch.tar.xz -C / \
    && tar -xvf /tmp/s6/s6-overlay.tar.xz -C / \
    && ln -s /init /s6-init

RUN set -x ; uname -a ; /command/s6-ls /

ENTRYPOINT ["/s6-init"]
