name: LWPM Dist K8S File

on:
  workflow_dispatch:
    inputs:
      LWPM_K8S_VERSION:
        description: k8s version
        required: true
        default: 1.34.0

env:
  LWPM_K8S_VERSION: ${{ github.event.inputs.LWPM_K8S_VERSION }}
  CODING_DOCKER_REGISTRY: docker.cnb.cool
  CODING_DOCKER_USERNAME: cnb
  CODING_DOCKER_PASSWORD: ${{secrets.CODING_DOCKER_PASSWORD}}

jobs:
  lwpm-dist-k8s-file:
    name: lwpm-dist-k8s-file
    runs-on: ${{ matrix.os }}-latest
    env:
      LWPM_DOCKER_USERNAME: khs1994
      LWPM_DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      LWPM_DOCKER_REGISTRY: registry-1.docker.io
      LNMP_CN_ENV: "false"
      GHCR_DOCKER_USERNAME: khs1994
      GHCR_DOCKER_PASSWORD: ${{secrets.GHCR_IO_TOKEN}}
      GHCR_DOCKER_REGISTRY: ghcr.io
    strategy:
      matrix:
        include:
          - os: "windows"
            pkg: "kubectl"
          - os: "windows"
            pkg: "kubernetes-node"
          - os: "ubuntu"
            pkg: "kubernetes-server"
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          repository: khs1994-docker/lnmp
          fetch-depth: 1
          path: lnmp
      - name: handle-${{ matrix.pkg }}
        shell: pwsh
        env:
          TENCENT_DOCKER_USERNAME: "906210846"
          TENCENT_DOCKER_REGISTRY: useccr.ccs.tencentyun.com
          PKG: ${{ matrix.pkg }}
        run: |
          echo $ErrorActionPreference
          $ErrorActionPreference = "Continue"
          . ./lnmp/windows/sdk/dockerhub/rootfs.ps1

          ./lnmp/windows/lnmp-windows-pm.ps1 dist ${ENV:PKG}@${env:LWPM_K8S_VERSION}
          ./lnmp/windows/lnmp-windows-pm.ps1 push ${ENV:PKG}@${env:LWPM_K8S_VERSION}

          $env:DOCKER_USERNAME="khs1994"
          rootfs lwpm/${ENV:PKG} ${env:LWPM_K8S_VERSION} -phase "manifest list"

          $env:LWPM_DOCKER_USERNAME=$env:TENCENT_DOCKER_USERNAME
          $env:LWPM_DOCKER_REGISTRY=$env:TENCENT_DOCKER_REGISTRY
          $NS="khs1994"
          ./lnmp/windows/lnmp-windows-pm.ps1 push $NS/${ENV:PKG}@${env:LWPM_K8S_VERSION}

          $env:DOCKER_USERNAME=$env:TENCENT_DOCKER_USERNAME
          rootfs $NS/${ENV:PKG} ${env:LWPM_K8S_VERSION} -registry $env:LWPM_DOCKER_REGISTRY -phase "manifest list"

          $env:LWPM_DOCKER_USERNAME=$env:CODING_DOCKER_USERNAME
          $env:LWPM_DOCKER_PASSWORD=$env:CODING_DOCKER_PASSWORD
          $env:LWPM_DOCKER_REGISTRY=$env:CODING_DOCKER_REGISTRY
          $NS="khs1994-docker/lwpm"
          ./lnmp/windows/lnmp-windows-pm.ps1 push $NS/${ENV:PKG}@${env:LWPM_K8S_VERSION}

          $env:LWPM_DOCKER_USERNAME=$env:GHCR_DOCKER_USERNAME
          $env:LWPM_DOCKER_PASSWORD=$env:GHCR_DOCKER_PASSWORD
          $env:LWPM_DOCKER_REGISTRY=$env:GHCR_DOCKER_REGISTRY
          $NS="khs1994"
          ./lnmp/windows/lnmp-windows-pm.ps1 push $NS/${ENV:PKG}@${env:LWPM_K8S_VERSION}
