name: runsc
version: nightly
url: "https://github.com/docker-practice/gvisor-mirror/releases/download/nightly/runsc-linux-amd64.tar.gz"
url-mirror: https://${env:GITHUB_MIRROR}/docker-practice/gvisor-mirror/releases/download/nightly/runsc-linux-amd64.tar.gz
scripts:
  platform-reqs: if(!$IsLinux){echo $False}
  dist: |
    _mkdir $env:LWPM_PKG_ROOT/dist

    curl -L `
      https://storage.googleapis.com/gvisor/releases/master/latest/x86_64/containerd-shim-runsc-v1 `
      -o $env:LWPM_PKG_ROOT/dist/containerd-shim-runsc-v1

    curl -L `
      https://storage.googleapis.com/gvisor/releases/master/latest/x86_64/runsc `
      -o $env:LWPM_PKG_ROOT/dist/runsc
platform:
  - architecture: amd64
    os: linux
